import type { CatalogEntry } from "./catalog";

const bearer = [{ name: "Authorization", location: "header", required: true }];
const key = (name: string) => [{ name, location: "header", required: true }];
const none: { name: string; location: string; required: boolean }[] = [];

/**
 * Fourth bootstrap wave — media, developer tooling, monitoring, official MCP
 * servers, productivity and infrastructure. No finance or market data.
 */
export const WAVE4_CATALOG: CatalogEntry[] = [
  /* ------------------------------------------- speech, audio, video */
  {
    slug: "assemblyai-api",
    name: "AssemblyAI",
    category: "api",
    summary: "Speech-to-text with diarisation, summaries and topic detection.",
    endpoint: "https://api.assemblyai.com/v2/transcript",
    docs_url: "https://www.assemblyai.com/docs/api-reference/transcripts",
    auth_mode: "Authorization header (api key)",
    auth_params: key("Authorization"),
    tags: ["speech", "audio"],
    capabilities: ["transcribe audio", "speech to text", "summarise audio", "speaker diarisation"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Concurrency based",
    pricing: "Free credits, then per hour",
  },
  {
    slug: "cartesia-api",
    name: "Cartesia",
    category: "api",
    summary: "Low-latency text-to-speech with voice cloning, built for realtime agents.",
    endpoint: "https://api.cartesia.ai/tts/bytes",
    docs_url: "https://docs.cartesia.ai/api-reference",
    auth_mode: "X-API-Key header",
    auth_params: key("X-API-Key"),
    tags: ["speech", "audio"],
    capabilities: ["text to speech", "voice synthesis", "realtime voice"],
    input_format: "application/json",
    output_format: "audio/mpeg or raw PCM",
    rate_limit: "Plan dependent",
    pricing: "Free tier credits",
  },
  {
    slug: "playht-api",
    name: "PlayHT",
    category: "api",
    summary: "Text-to-speech and voice cloning with a streaming endpoint.",
    endpoint: "https://api.play.ht/api/v2/tts",
    docs_url: "https://docs.play.ai/tts-api-reference",
    auth_mode: "Authorization + X-User-ID headers",
    auth_params: key("Authorization"),
    tags: ["speech", "audio"],
    capabilities: ["text to speech", "voice cloning", "voice synthesis"],
    input_format: "application/json",
    output_format: "audio/mpeg",
    rate_limit: "Plan dependent",
    pricing: "Free trial characters",
  },
  {
    slug: "whisper-cpp-cli",
    name: "whisper.cpp",
    category: "cli",
    summary: "Local speech-to-text on CPU, no network and no API key.",
    endpoint: "whisper-cli -m models/ggml-base.bin -f audio.wav",
    docs_url: "https://github.com/ggml-org/whisper.cpp",
    auth_mode: "None",
    tags: ["speech", "audio"],
    capabilities: ["transcribe audio", "speech to text", "offline transcription"],
    input_format: "CLI arguments + audio file",
    output_format: "Text / SRT / VTT files",
    rate_limit: "Local CPU bound",
    pricing: "Free (MIT)",
  },
  {
    slug: "sox-cli",
    name: "SoX",
    category: "cli",
    summary: "Swiss-army knife of audio: convert formats, trim, resample, apply effects.",
    endpoint: "sox input.wav output.mp3 rate 16000",
    docs_url: "https://sox.sourceforge.net/sox.html",
    auth_mode: "None",
    tags: ["audio", "conversion"],
    capabilities: ["convert audio", "resample audio", "trim audio", "audio effects"],
    input_format: "CLI arguments + audio files",
    output_format: "Audio files",
    rate_limit: "Local CPU bound",
    pricing: "Free (GPL)",
  },
  {
    slug: "mux-video-api",
    name: "Mux Video",
    category: "api",
    summary: "Upload, encode and stream video with per-asset playback IDs.",
    endpoint: "https://api.mux.com/video/v1/assets",
    docs_url: "https://docs.mux.com/api-reference",
    auth_mode: "HTTP Basic (token id + secret)",
    auth_params: key("Authorization"),
    tags: ["video", "streaming"],
    capabilities: ["upload video", "encode video", "stream video", "video thumbnails"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free trial credit",
  },
  {
    slug: "cloudflare-stream-api",
    name: "Cloudflare Stream",
    category: "api",
    summary: "Video ingest, encoding and delivery on Cloudflare's network.",
    endpoint: "https://api.cloudflare.com/client/v4/accounts/<account>/stream",
    docs_url: "https://developers.cloudflare.com/api/resources/stream/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["video", "streaming"],
    capabilities: ["upload video", "stream video", "encode video"],
    input_format: "application/json or multipart",
    output_format: "application/json",
    rate_limit: "1,200 req / 5 min",
    pricing: "Per minute stored/delivered",
  },
  {
    slug: "shotstack-api",
    name: "Shotstack",
    category: "api",
    summary: "Render videos programmatically from a JSON edit timeline.",
    endpoint: "https://api.shotstack.io/edit/stage/render",
    docs_url: "https://shotstack.io/docs/api/",
    auth_mode: "x-api-key header",
    auth_params: key("x-api-key"),
    tags: ["video", "generation"],
    capabilities: ["render video", "edit video", "generate video"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free sandbox environment",
  },
  {
    slug: "livekit-api",
    name: "LiveKit",
    category: "api",
    summary: "Realtime audio/video rooms and agent sessions over WebRTC.",
    endpoint: "https://<project>.livekit.cloud/twirp/livekit.RoomService/CreateRoom",
    docs_url: "https://docs.livekit.io/reference/server/server-apis/",
    auth_mode: "Bearer JWT signed with API secret",
    auth_params: bearer,
    tags: ["video", "realtime"],
    capabilities: ["create video room", "realtime audio", "voice agent session"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier, open source server",
  },
  {
    slug: "daily-co-api",
    name: "Daily",
    category: "api",
    summary: "Create video-call rooms and tokens with one REST call.",
    endpoint: "https://api.daily.co/v1/rooms",
    docs_url: "https://docs.daily.co/reference/rest-api",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["video", "realtime"],
    capabilities: ["create video room", "realtime audio", "video call"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "10k free minutes/month",
  },

  /* ------------------------------------------- images & visual generation */
  {
    slug: "fal-ai-api",
    name: "fal.ai",
    category: "api",
    summary: "Hosted inference for image, video and audio models with a queue API.",
    endpoint: "https://fal.run/fal-ai/flux/dev",
    docs_url: "https://docs.fal.ai/model-endpoints",
    auth_mode: "Key authorization header",
    auth_params: key("Authorization"),
    tags: ["images", "generation"],
    capabilities: ["generate image", "image to image", "run model inference", "generate video"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Concurrency based",
    pricing: "Pay per second of compute",
  },
  {
    slug: "stability-ai-api",
    name: "Stability AI",
    category: "api",
    summary: "Stable Diffusion image generation, upscaling and editing endpoints.",
    endpoint: "https://api.stability.ai/v2beta/stable-image/generate/core",
    docs_url: "https://platform.stability.ai/docs/api-reference",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["images", "generation"],
    capabilities: ["generate image", "upscale image", "edit image", "remove background"],
    input_format: "multipart/form-data",
    output_format: "image/* or application/json",
    rate_limit: "150 req/10s",
    pricing: "Credit based",
  },
  {
    slug: "removebg-api",
    name: "remove.bg",
    category: "api",
    summary: "Cut out the background of a photo in one call.",
    endpoint: "https://api.remove.bg/v1.0/removebg",
    docs_url: "https://www.remove.bg/api",
    auth_mode: "X-Api-Key header",
    auth_params: key("X-Api-Key"),
    tags: ["images", "editing"],
    capabilities: ["remove background", "edit image", "cut out subject"],
    input_format: "multipart/form-data",
    output_format: "image/png",
    rate_limit: "500 req/min",
    pricing: "50 free previews/month",
  },
  {
    slug: "cloudinary-api",
    name: "Cloudinary",
    category: "api",
    summary: "Image and video upload with on-the-fly transformation URLs.",
    endpoint: "https://api.cloudinary.com/v1_1/<cloud_name>/image/upload",
    docs_url: "https://cloudinary.com/documentation/image_upload_api_reference",
    auth_mode: "API key + signature or HTTP Basic",
    auth_params: key("Authorization"),
    tags: ["images", "storage"],
    capabilities: ["upload image", "resize image", "transform image", "optimise image"],
    input_format: "multipart/form-data",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier 25 credits/month",
  },
  {
    slug: "tinypng-api",
    name: "TinyPNG",
    category: "api",
    summary: "Lossy compression for PNG, JPEG and WebP with resizing.",
    endpoint: "https://api.tinify.com/shrink",
    docs_url: "https://tinypng.com/developers/reference",
    auth_mode: "HTTP Basic (api key)",
    auth_params: key("Authorization"),
    tags: ["images", "optimisation"],
    capabilities: ["compress image", "optimise image", "resize image"],
    input_format: "Binary image body",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "500 free compressions/month",
  },
  {
    slug: "screenshotone-api",
    name: "ScreenshotOne",
    category: "api",
    summary: "Render any URL to a PNG, JPEG or PDF screenshot with one GET.",
    endpoint: "https://api.screenshotone.com/take",
    docs_url: "https://screenshotone.com/docs/",
    auth_mode: "access_key query parameter",
    auth_params: [{ name: "access_key", location: "query", required: true }],
    tags: ["screenshot", "web"],
    capabilities: ["take screenshot", "url to image", "render webpage", "url to pdf"],
    input_format: "Query parameters",
    output_format: "image/png or application/pdf",
    rate_limit: "Plan dependent",
    pricing: "100 free screenshots/month",
  },
  {
    slug: "urlbox-api",
    name: "Urlbox",
    category: "api",
    summary: "Website screenshots and PDFs with full-page, retina and blocking options.",
    endpoint: "https://api.urlbox.com/v1/render/sync",
    docs_url: "https://urlbox.com/docs/api",
    auth_mode: "Bearer API secret",
    auth_params: bearer,
    tags: ["screenshot", "web"],
    capabilities: ["take screenshot", "url to image", "url to pdf", "render webpage"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free trial renders",
  },
  {
    slug: "microlink-api",
    name: "Microlink",
    category: "api",
    summary: "Turn any URL into metadata, a screenshot, a PDF or reader-mode content.",
    endpoint: "https://api.microlink.io/",
    docs_url: "https://microlink.io/docs/api/getting-started/overview",
    auth_mode: "None for the free tier",
    auth_params: none,
    tags: ["web", "metadata"],
    capabilities: ["extract page metadata", "take screenshot", "read article", "url to pdf"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "50 req/day free, 1 req/s",
    pricing: "Free tier",
    invocation_example: "curl 'https://api.microlink.io/?url=https://agentnexus.app'",
  },
  {
    slug: "bannerbear-api",
    name: "Bannerbear",
    category: "api",
    summary: "Generate branded images and video from templates via API.",
    endpoint: "https://api.bannerbear.com/v2/images",
    docs_url: "https://developers.bannerbear.com/",
    auth_mode: "Bearer project key",
    auth_params: bearer,
    tags: ["images", "generation"],
    capabilities: ["generate image", "template image", "social image"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free trial credits",
  },
  {
    slug: "exiftool-cli",
    name: "ExifTool",
    category: "cli",
    summary: "Read, write and strip metadata in images, video and documents.",
    endpoint: "exiftool -all= photo.jpg",
    docs_url: "https://exiftool.org/exiftool_pod.html",
    auth_mode: "None",
    tags: ["images", "metadata"],
    capabilities: ["read metadata", "strip metadata", "edit exif"],
    input_format: "CLI arguments + media files",
    output_format: "Text / JSON on stdout",
    rate_limit: "Local CPU bound",
    pricing: "Free (Artistic/GPL)",
  },
  {
    slug: "svgo-cli",
    name: "SVGO",
    category: "cli",
    summary: "Optimise SVG files by removing redundant markup.",
    endpoint: "svgo input.svg -o output.svg",
    docs_url: "https://svgo.dev/docs/introduction/",
    auth_mode: "None",
    tags: ["images", "optimisation"],
    capabilities: ["optimise svg", "compress image", "clean markup"],
    input_format: "CLI arguments + SVG files",
    output_format: "SVG files",
    rate_limit: "Local CPU bound",
    pricing: "Free (MIT)",
  },
  {
    slug: "gifsicle-cli",
    name: "Gifsicle",
    category: "cli",
    summary: "Create, optimise and edit animated GIFs from the command line.",
    endpoint: "gifsicle --optimize=3 in.gif -o out.gif",
    docs_url: "https://www.lcdf.org/gifsicle/man.html",
    auth_mode: "None",
    tags: ["images", "optimisation"],
    capabilities: ["optimise gif", "create animation", "compress image"],
    input_format: "CLI arguments + GIF files",
    output_format: "GIF files",
    rate_limit: "Local CPU bound",
    pricing: "Free (GPL)",
  },

  /* ------------------------------------------- monitoring & observability */
  {
    slug: "uptimerobot-api",
    name: "UptimeRobot",
    category: "api",
    summary: "Create and read uptime monitors and incidents over a REST API.",
    endpoint: "https://api.uptimerobot.com/v2/getMonitors",
    docs_url: "https://uptimerobot.com/api/",
    auth_mode: "api_key in body",
    auth_params: [{ name: "api_key", location: "body", required: true }],
    tags: ["monitoring", "uptime"],
    capabilities: ["monitor uptime", "check endpoint health", "read incidents"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "10 req/min free",
    pricing: "Free tier 50 monitors",
  },
  {
    slug: "betterstack-uptime-api",
    name: "Better Stack Uptime",
    category: "api",
    summary: "Uptime monitors, heartbeats and on-call incidents via API.",
    endpoint: "https://uptime.betterstack.com/api/v2/monitors",
    docs_url: "https://betterstack.com/docs/uptime/api/getting-started-with-uptime-api/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["monitoring", "uptime"],
    capabilities: ["monitor uptime", "heartbeat check", "incident management"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier 10 monitors",
  },
  {
    slug: "healthchecks-io-api",
    name: "Healthchecks.io",
    category: "api",
    summary: "Dead-man's-switch monitoring for cron jobs and scheduled agents.",
    endpoint: "https://hc-ping.com/<uuid>",
    docs_url: "https://healthchecks.io/docs/http_api/",
    auth_mode: "None for pings, X-Api-Key for management",
    auth_params: none,
    tags: ["monitoring", "cron"],
    capabilities: ["heartbeat check", "monitor cron job", "alert on failure"],
    input_format: "Plain GET/POST",
    output_format: "text/plain",
    rate_limit: "Fair use",
    pricing: "Free tier 20 checks, open source",
    invocation_example: "curl https://hc-ping.com/<uuid>",
  },
  {
    slug: "cronitor-api",
    name: "Cronitor",
    category: "api",
    summary: "Monitors cron jobs, queues and endpoints with telemetry pings.",
    endpoint: "https://cronitor.link/p/<api_key>/<monitor_key>",
    docs_url: "https://cronitor.io/docs/telemetry-api",
    auth_mode: "API key in path",
    auth_params: none,
    tags: ["monitoring", "cron"],
    capabilities: ["monitor cron job", "heartbeat check", "alert on failure"],
    input_format: "Query parameters",
    output_format: "text/plain",
    rate_limit: "Plan dependent",
    pricing: "Free tier 5 monitors",
  },
  {
    slug: "prometheus-http-api",
    name: "Prometheus HTTP API",
    category: "api",
    summary: "Query time-series metrics with PromQL against any Prometheus server.",
    endpoint: "http://<host>:9090/api/v1/query",
    docs_url: "https://prometheus.io/docs/prometheus/latest/querying/api/",
    auth_mode: "None (deploy behind your own gate)",
    auth_params: none,
    tags: ["monitoring", "metrics"],
    capabilities: ["query metrics", "read time series", "monitor system"],
    input_format: "Query parameters (PromQL)",
    output_format: "application/json",
    rate_limit: "Self-hosted",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "grafana-http-api",
    name: "Grafana HTTP API",
    category: "api",
    summary: "Manage dashboards, datasources, alerts and annotations programmatically.",
    endpoint: "https://<grafana-host>/api/dashboards/db",
    docs_url: "https://grafana.com/docs/grafana/latest/developers/http_api/",
    auth_mode: "Bearer service account token",
    auth_params: bearer,
    tags: ["monitoring", "dashboards"],
    capabilities: ["manage dashboards", "create annotation", "read alerts"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Instance configured",
    pricing: "Free OSS, hosted free tier",
  },
  {
    slug: "datadog-api",
    name: "Datadog",
    category: "api",
    summary: "Submit and query metrics, logs, events and monitors.",
    endpoint: "https://api.datadoghq.com/api/v2/series",
    docs_url: "https://docs.datadoghq.com/api/latest/",
    auth_mode: "DD-API-KEY header",
    auth_params: key("DD-API-KEY"),
    tags: ["monitoring", "metrics"],
    capabilities: ["submit metrics", "query metrics", "send logs", "manage monitors"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Endpoint dependent",
    pricing: "Free trial, per host",
  },
  {
    slug: "newrelic-api",
    name: "New Relic",
    category: "api",
    summary: "Ingest events and metrics, and query them with NRQL via GraphQL.",
    endpoint: "https://insights-collector.newrelic.com/v1/accounts/<account>/events",
    docs_url: "https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/",
    auth_mode: "Api-Key header",
    auth_params: key("Api-Key"),
    tags: ["monitoring", "metrics"],
    capabilities: ["submit metrics", "query metrics", "send events"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Free 100 GB/month ingest",
  },
  {
    slug: "k6-cli",
    name: "k6",
    category: "cli",
    summary: "Scriptable load testing for HTTP APIs with thresholds and summaries.",
    endpoint: "k6 run script.js",
    docs_url: "https://grafana.com/docs/k6/latest/",
    auth_mode: "None",
    tags: ["testing", "performance"],
    capabilities: ["load test", "performance test", "benchmark api"],
    input_format: "CLI arguments + JS script",
    output_format: "Text / JSON summary",
    rate_limit: "Local resource bound",
    pricing: "Free (AGPL)",
  },
  {
    slug: "httpie-cli",
    name: "HTTPie",
    category: "cli",
    summary: "Human-friendly HTTP client with JSON defaults and coloured output.",
    endpoint: "http POST api.example.com/items name=foo",
    docs_url: "https://httpie.io/docs/cli",
    auth_mode: "None",
    tags: ["http", "developer-tools"],
    capabilities: ["call http api", "inspect response", "debug request"],
    input_format: "CLI arguments",
    output_format: "Coloured HTTP response on stdout",
    rate_limit: "Local",
    pricing: "Free (BSD)",
  },
  {
    slug: "grpcurl-cli",
    name: "grpcurl",
    category: "cli",
    summary: "curl for gRPC: list services and call methods using reflection.",
    endpoint: "grpcurl -plaintext host:50051 list",
    docs_url: "https://github.com/fullstorydev/grpcurl",
    auth_mode: "None",
    tags: ["grpc", "developer-tools"],
    capabilities: ["call grpc service", "list grpc methods", "debug request"],
    input_format: "CLI arguments",
    output_format: "JSON on stdout",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "websocat-cli",
    name: "websocat",
    category: "cli",
    summary: "netcat for WebSockets: connect, send and pipe frames from the shell.",
    endpoint: "websocat wss://echo.websocket.org",
    docs_url: "https://github.com/vi/websocat",
    auth_mode: "None",
    tags: ["websocket", "developer-tools"],
    capabilities: ["connect websocket", "send websocket message", "debug request"],
    input_format: "CLI arguments + stdin",
    output_format: "Frames on stdout",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },

  /* ------------------------------------------- security & code quality */
  {
    slug: "haveibeenpwned-api",
    name: "Have I Been Pwned",
    category: "api",
    summary: "Check whether an email or password appears in known breaches.",
    endpoint: "https://haveibeenpwned.com/api/v3/breachedaccount/<account>",
    docs_url: "https://haveibeenpwned.com/API/v3",
    auth_mode: "hibp-api-key header (range API is keyless)",
    auth_params: key("hibp-api-key"),
    tags: ["security", "breach"],
    capabilities: ["check breach", "password exposure check", "account security"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Key tier dependent",
    pricing: "Paid key; Pwned Passwords range API free",
  },
  {
    slug: "abuseipdb-api",
    name: "AbuseIPDB",
    category: "api",
    summary: "Reputation and abuse reports for any IP address.",
    endpoint: "https://api.abuseipdb.com/api/v2/check",
    docs_url: "https://docs.abuseipdb.com/",
    auth_mode: "Key header",
    auth_params: key("Key"),
    tags: ["security", "threat-intel"],
    capabilities: ["check ip reputation", "threat intelligence", "detect abuse"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1,000 checks/day free",
    pricing: "Free tier",
  },
  {
    slug: "greynoise-community-api",
    name: "GreyNoise Community",
    category: "api",
    summary: "Tells you whether an IP is internet-wide background noise or targeted.",
    endpoint: "https://api.greynoise.io/v3/community/<ip>",
    docs_url: "https://docs.greynoise.io/docs/using-the-community-api",
    auth_mode: "key header (free community key)",
    auth_params: key("key"),
    tags: ["security", "threat-intel"],
    capabilities: ["check ip reputation", "threat intelligence", "scanner detection"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "50 lookups/week on the community tier",
    pricing: "Free community tier",
  },
  {
    slug: "shodan-api",
    name: "Shodan",
    category: "api",
    summary: "Search internet-exposed hosts, services and banners.",
    endpoint: "https://api.shodan.io/shodan/host/<ip>",
    docs_url: "https://developer.shodan.io/api",
    auth_mode: "key query parameter",
    auth_params: [{ name: "key", location: "query", required: true }],
    tags: ["security", "recon"],
    capabilities: ["scan host", "search exposed services", "attack surface discovery"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 req/s",
    pricing: "Paid membership",
  },
  {
    slug: "otx-alienvault-api",
    name: "AlienVault OTX",
    category: "api",
    summary: "Open threat exchange indicators for IPs, domains, files and URLs.",
    endpoint: "https://otx.alienvault.com/api/v1/indicators/IPv4/<ip>/general",
    docs_url: "https://otx.alienvault.com/api",
    auth_mode: "X-OTX-API-KEY header",
    auth_params: key("X-OTX-API-KEY"),
    tags: ["security", "threat-intel"],
    capabilities: ["threat intelligence", "check indicator", "check ip reputation"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "10k req/hour",
    pricing: "Free",
  },
  {
    slug: "ssllabs-api",
    name: "SSL Labs",
    category: "api",
    summary: "Deep TLS configuration assessment of any public HTTPS host.",
    endpoint: "https://api.ssllabs.com/api/v3/analyze",
    docs_url: "https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md",
    auth_mode: "None",
    auth_params: none,
    tags: ["security", "tls"],
    capabilities: ["check tls configuration", "certificate audit", "security scan"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 assessment at a time, 25/hour",
    pricing: "Free for non-commercial use",
    invocation_example: "curl 'https://api.ssllabs.com/api/v3/analyze?host=agentnexus.app'",
  },
  {
    slug: "mozilla-observatory-api",
    name: "Mozilla HTTP Observatory",
    category: "api",
    summary: "Grades a site's HTTP security headers and configuration.",
    endpoint: "https://observatory-api.mdn.mozilla.net/api/v2/scan",
    docs_url: "https://developer.mozilla.org/en-US/observatory/docs/tests_and_scoring",
    auth_mode: "None",
    auth_params: none,
    tags: ["security", "web"],
    capabilities: ["security scan", "check security headers", "audit website"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free",
  },
  {
    slug: "rdap-api",
    name: "RDAP (rdap.org)",
    category: "api",
    summary: "Structured domain and IP registration data, the JSON successor to WHOIS.",
    endpoint: "https://rdap.org/domain/<domain>",
    docs_url: "https://about.rdap.org/",
    auth_mode: "None",
    auth_params: none,
    tags: ["dns", "domains"],
    capabilities: ["whois lookup", "domain registration data", "ip allocation data"],
    input_format: "Path parameters",
    output_format: "application/rdap+json",
    rate_limit: "Registry dependent",
    pricing: "Free",
    invocation_example: "curl https://rdap.org/domain/agentnexus.app",
  },
  {
    slug: "trivy-cli",
    name: "Trivy",
    category: "cli",
    summary: "Scan containers, filesystems and repos for CVEs, secrets and misconfiguration.",
    endpoint: "trivy image nginx:latest",
    docs_url: "https://trivy.dev/latest/docs/",
    auth_mode: "None",
    tags: ["security", "scanning"],
    capabilities: ["vulnerability scan", "scan container image", "detect secrets", "sbom"],
    input_format: "CLI arguments",
    output_format: "Table / JSON / SARIF",
    rate_limit: "Local CPU bound",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "syft-cli",
    name: "Syft",
    category: "cli",
    summary: "Generate an SBOM from an image or directory in SPDX or CycloneDX.",
    endpoint: "syft dir:. -o spdx-json",
    docs_url: "https://github.com/anchore/syft",
    auth_mode: "None",
    tags: ["security", "sbom"],
    capabilities: ["generate sbom", "inventory dependencies", "supply chain audit"],
    input_format: "CLI arguments",
    output_format: "SPDX / CycloneDX JSON",
    rate_limit: "Local CPU bound",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "grype-cli",
    name: "Grype",
    category: "cli",
    summary: "Match an SBOM or image against vulnerability databases.",
    endpoint: "grype dir:.",
    docs_url: "https://github.com/anchore/grype",
    auth_mode: "None",
    tags: ["security", "scanning"],
    capabilities: ["vulnerability scan", "scan container image", "supply chain audit"],
    input_format: "CLI arguments",
    output_format: "Table / JSON",
    rate_limit: "Local CPU bound",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "gitleaks-cli",
    name: "Gitleaks",
    category: "cli",
    summary: "Detect hardcoded secrets in git history and working trees.",
    endpoint: "gitleaks detect --source .",
    docs_url: "https://github.com/gitleaks/gitleaks",
    auth_mode: "None",
    tags: ["security", "secrets"],
    capabilities: ["detect secrets", "scan repository", "security scan"],
    input_format: "CLI arguments",
    output_format: "Text / JSON / SARIF",
    rate_limit: "Local CPU bound",
    pricing: "Free (MIT)",
  },
  {
    slug: "trufflehog-cli",
    name: "TruffleHog",
    category: "cli",
    summary: "Finds and verifies live credentials across repos, buckets and files.",
    endpoint: "trufflehog filesystem .",
    docs_url: "https://github.com/trufflesecurity/trufflehog",
    auth_mode: "None",
    tags: ["security", "secrets"],
    capabilities: ["detect secrets", "verify credentials", "scan repository"],
    input_format: "CLI arguments",
    output_format: "Text / JSON",
    rate_limit: "Local CPU bound",
    pricing: "Free (AGPL)",
  },
  {
    slug: "shellcheck-cli",
    name: "ShellCheck",
    category: "cli",
    summary: "Static analysis for shell scripts that catches quoting and portability bugs.",
    endpoint: "shellcheck script.sh",
    docs_url: "https://www.shellcheck.net/wiki/",
    auth_mode: "None",
    tags: ["linting", "developer-tools"],
    capabilities: ["lint shell script", "static analysis", "code review"],
    input_format: "CLI arguments",
    output_format: "Text / JSON diagnostics",
    rate_limit: "Local",
    pricing: "Free (GPL)",
  },
  {
    slug: "hadolint-cli",
    name: "Hadolint",
    category: "cli",
    summary: "Dockerfile linter enforcing best practices and shell correctness.",
    endpoint: "hadolint Dockerfile",
    docs_url: "https://github.com/hadolint/hadolint",
    auth_mode: "None",
    tags: ["linting", "containers"],
    capabilities: ["lint dockerfile", "static analysis", "code review"],
    input_format: "CLI arguments",
    output_format: "Text / JSON diagnostics",
    rate_limit: "Local",
    pricing: "Free (GPL)",
  },
  {
    slug: "ruff-cli",
    name: "Ruff",
    category: "cli",
    summary: "Extremely fast Python linter and formatter.",
    endpoint: "ruff check .",
    docs_url: "https://docs.astral.sh/ruff/",
    auth_mode: "None",
    tags: ["linting", "python"],
    capabilities: ["lint python", "format code", "static analysis"],
    input_format: "CLI arguments",
    output_format: "Text / JSON diagnostics",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "biome-cli",
    name: "Biome",
    category: "cli",
    summary: "One fast toolchain that lints and formats JS, TS, JSON and CSS.",
    endpoint: "biome check .",
    docs_url: "https://biomejs.dev/reference/cli/",
    auth_mode: "None",
    tags: ["linting", "javascript"],
    capabilities: ["lint javascript", "format code", "static analysis"],
    input_format: "CLI arguments",
    output_format: "Text / JSON diagnostics",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "eslint-cli",
    name: "ESLint",
    category: "cli",
    summary: "Configurable JavaScript and TypeScript linter with autofix.",
    endpoint: "eslint . --fix",
    docs_url: "https://eslint.org/docs/latest/use/command-line-interface",
    auth_mode: "None",
    tags: ["linting", "javascript"],
    capabilities: ["lint javascript", "autofix code", "static analysis"],
    input_format: "CLI arguments",
    output_format: "Text / JSON diagnostics",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "vitest-cli",
    name: "Vitest",
    category: "cli",
    summary: "Vite-native test runner with watch mode and coverage.",
    endpoint: "vitest run --coverage",
    docs_url: "https://vitest.dev/guide/cli.html",
    auth_mode: "None",
    tags: ["testing", "javascript"],
    capabilities: ["run tests", "test coverage", "verify code"],
    input_format: "CLI arguments",
    output_format: "Text / JSON report",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "pytest-cli",
    name: "pytest",
    category: "cli",
    summary: "Python test runner with fixtures, parametrisation and plugins.",
    endpoint: "pytest -q",
    docs_url: "https://docs.pytest.org/en/stable/how-to/usage.html",
    auth_mode: "None",
    tags: ["testing", "python"],
    capabilities: ["run tests", "test coverage", "verify code"],
    input_format: "CLI arguments",
    output_format: "Text / JUnit XML report",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },

  /* ------------------------------------------- official & popular MCP servers */
  {
    slug: "time-mcp-server",
    name: "Time MCP server",
    category: "mcp",
    summary: "Reference MCP server for current time and timezone conversion.",
    endpoint: "npx -y @modelcontextprotocol/server-time",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
    auth_mode: "None (stdio)",
    tags: ["mcp", "time"],
    capabilities: ["get current time", "convert timezone", "date arithmetic"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "everything-mcp-server",
    name: "Everything MCP server",
    category: "mcp",
    summary: "Reference server exercising every MCP feature — ideal for client testing.",
    endpoint: "npx -y @modelcontextprotocol/server-everything",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    auth_mode: "None (stdio)",
    tags: ["mcp", "testing"],
    capabilities: ["test mcp client", "sample tools", "sample prompts", "sample resources"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "git-mcp-server",
    name: "Git MCP server",
    category: "mcp",
    summary: "Official MCP server exposing git status, diff, log, commit and branches.",
    endpoint: "uvx mcp-server-git --repository /path/to/repo",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    auth_mode: "None (local filesystem)",
    tags: ["mcp", "git"],
    capabilities: ["read git history", "git diff", "commit changes", "manage branches"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "sqlite-mcp-server",
    name: "SQLite MCP server",
    category: "mcp",
    summary: "Query and mutate a local SQLite database through MCP tools.",
    endpoint: "uvx mcp-server-sqlite --db-path ./data.db",
    docs_url: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite",
    auth_mode: "None (local file)",
    tags: ["mcp", "database"],
    capabilities: ["query database", "run sql", "inspect schema"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "redis-mcp-server",
    name: "Redis MCP server",
    category: "mcp",
    summary: "Official Redis MCP server for keys, hashes, streams and vector search.",
    endpoint: "uvx --from redis-mcp-server redis-mcp-server",
    docs_url: "https://github.com/redis/mcp-redis",
    auth_mode: "Redis connection URL",
    tags: ["mcp", "database"],
    capabilities: ["read cache", "write key", "query redis", "vector search"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Server dependent",
    pricing: "Free (MIT)",
  },
  {
    slug: "qdrant-mcp-server",
    name: "Qdrant MCP server",
    category: "mcp",
    summary: "Store and retrieve embeddings in Qdrant as agent memory.",
    endpoint: "uvx mcp-server-qdrant",
    docs_url: "https://github.com/qdrant/mcp-server-qdrant",
    auth_mode: "Qdrant URL + API key env vars",
    tags: ["mcp", "vector-search"],
    capabilities: ["store memory", "semantic search", "vector search", "retrieve documents"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Cluster dependent",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "chroma-mcp-server",
    name: "Chroma MCP server",
    category: "mcp",
    summary: "Chroma vector database as an MCP server for retrieval and memory.",
    endpoint: "uvx chroma-mcp",
    docs_url: "https://github.com/chroma-core/chroma-mcp",
    auth_mode: "None locally, API key for Chroma Cloud",
    tags: ["mcp", "vector-search"],
    capabilities: ["store memory", "semantic search", "vector search", "retrieve documents"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Deployment dependent",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "elasticsearch-mcp-server",
    name: "Elasticsearch MCP server",
    category: "mcp",
    summary: "Official server letting an agent query Elasticsearch indices in natural language.",
    endpoint: "npx -y @elastic/mcp-server-elasticsearch",
    docs_url: "https://github.com/elastic/mcp-server-elasticsearch",
    auth_mode: "Elasticsearch URL + API key env vars",
    tags: ["mcp", "search"],
    capabilities: ["search index", "query elasticsearch", "inspect mappings"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Cluster dependent",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "clickhouse-mcp-server",
    name: "ClickHouse MCP server",
    category: "mcp",
    summary: "Official read-oriented MCP server for ClickHouse analytics queries.",
    endpoint: "uv run --with mcp-clickhouse mcp-clickhouse",
    docs_url: "https://github.com/ClickHouse/mcp-clickhouse",
    auth_mode: "Host, user and password env vars",
    tags: ["mcp", "analytics"],
    capabilities: ["query database", "run sql", "analytics query", "inspect schema"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Cluster dependent",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "kubernetes-mcp-server",
    name: "Kubernetes MCP server",
    category: "mcp",
    summary: "Inspect and operate Kubernetes clusters through MCP tools.",
    endpoint: "npx -y mcp-server-kubernetes",
    docs_url: "https://github.com/Flux159/mcp-server-kubernetes",
    auth_mode: "Local kubeconfig",
    tags: ["mcp", "infrastructure"],
    capabilities: ["list pods", "read logs", "apply manifest", "operate cluster"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Cluster dependent",
    pricing: "Free (MIT)",
  },
  {
    slug: "terraform-mcp-server",
    name: "Terraform MCP server",
    category: "mcp",
    summary: "HashiCorp's server for provider docs, modules and registry lookups.",
    endpoint: "docker run -i hashicorp/terraform-mcp-server",
    docs_url: "https://github.com/hashicorp/terraform-mcp-server",
    auth_mode: "None for registry reads",
    tags: ["mcp", "infrastructure"],
    capabilities: ["search modules", "read provider docs", "infrastructure as code"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Registry fair use",
    pricing: "Free (MPL-2.0)",
  },
  {
    slug: "aws-mcp-servers",
    name: "AWS MCP Servers",
    category: "mcp",
    summary: "AWS Labs collection: docs, cost, CDK, Lambda and service-specific MCP servers.",
    endpoint: "uvx awslabs.aws-documentation-mcp-server@latest",
    docs_url: "https://github.com/awslabs/mcp",
    auth_mode: "AWS credentials for service servers",
    tags: ["mcp", "cloud"],
    capabilities: ["read aws docs", "query aws resources", "cloud operations"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "AWS account limits",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "azure-mcp-server",
    name: "Azure MCP server",
    category: "mcp",
    summary: "Microsoft's MCP server for Azure resources, storage, Cosmos DB and monitoring.",
    endpoint: "npx -y @azure/mcp@latest server start",
    docs_url: "https://github.com/microsoft/mcp",
    auth_mode: "Azure identity / service principal",
    tags: ["mcp", "cloud"],
    capabilities: ["query azure resources", "cloud operations", "read logs"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Azure account limits",
    pricing: "Free (MIT)",
  },
  {
    slug: "grafana-mcp-server",
    name: "Grafana MCP server",
    category: "mcp",
    summary: "Official server for dashboards, Prometheus/Loki queries and incidents.",
    endpoint: "npx -y @grafana/mcp-server-grafana",
    docs_url: "https://github.com/grafana/mcp-grafana",
    auth_mode: "Grafana URL + service account token",
    tags: ["mcp", "monitoring"],
    capabilities: ["query metrics", "read dashboards", "search logs", "incident response"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Instance configured",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "figma-mcp-server",
    name: "Figma MCP server",
    category: "mcp",
    summary: "Figma's Dev Mode server exposing selected frames, variables and code hints.",
    endpoint: "http://127.0.0.1:3845/mcp",
    docs_url: "https://help.figma.com/hc/en-us/articles/32132100833559",
    auth_mode: "Local Figma desktop session",
    tags: ["mcp", "design"],
    capabilities: ["read design file", "export design tokens", "design to code"],
    input_format: "MCP over HTTP",
    output_format: "MCP tool results",
    rate_limit: "Local desktop app",
    pricing: "Included with Figma Dev Mode",
  },
  {
    slug: "todoist-mcp-server",
    name: "Todoist MCP server",
    category: "mcp",
    summary: "Create, complete and search Todoist tasks from an agent.",
    endpoint: "npx -y @doist/todoist-mcp",
    docs_url: "https://github.com/Doist/todoist-mcp",
    auth_mode: "Todoist API token env var",
    tags: ["mcp", "productivity"],
    capabilities: ["create task", "complete task", "list tasks", "manage projects"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Todoist API limits",
    pricing: "Free (MIT)",
  },
  {
    slug: "airtable-mcp-server",
    name: "Airtable MCP server",
    category: "mcp",
    summary: "Read and write Airtable bases, tables and records through MCP.",
    endpoint: "npx -y airtable-mcp-server",
    docs_url: "https://github.com/domdomegg/airtable-mcp-server",
    auth_mode: "Airtable personal access token env var",
    tags: ["mcp", "database"],
    capabilities: ["read records", "create record", "query base", "inspect schema"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Airtable API limits",
    pricing: "Free (MIT)",
  },
  {
    slug: "obsidian-mcp-server",
    name: "Obsidian MCP server",
    category: "mcp",
    summary: "Search and edit an Obsidian vault via the Local REST API plugin.",
    endpoint: "npx -y mcp-obsidian",
    docs_url: "https://github.com/MarkusPfundstein/mcp-obsidian",
    auth_mode: "Obsidian Local REST API key",
    tags: ["mcp", "notes"],
    capabilities: ["search notes", "read note", "write note", "knowledge base"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "Local",
    pricing: "Free (MIT)",
  },
  {
    slug: "home-assistant-mcp-server",
    name: "Home Assistant MCP server",
    category: "mcp",
    summary: "Expose smart-home entities and services to an agent.",
    endpoint: "https://<ha-host>/mcp_server/sse",
    docs_url: "https://www.home-assistant.io/integrations/mcp_server/",
    auth_mode: "Bearer long-lived access token",
    tags: ["mcp", "iot"],
    capabilities: ["control devices", "read sensor state", "home automation"],
    input_format: "MCP over SSE",
    output_format: "MCP tool results",
    rate_limit: "Instance dependent",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "youtube-transcript-mcp-server",
    name: "YouTube Transcript MCP server",
    category: "mcp",
    summary: "Fetch transcripts and captions for YouTube videos.",
    endpoint: "npx -y @kimtaeyoon83/mcp-server-youtube-transcript",
    docs_url: "https://github.com/kimtaeyoon83/mcp-server-youtube-transcript",
    auth_mode: "None",
    tags: ["mcp", "video"],
    capabilities: ["fetch transcript", "read captions", "summarise video"],
    input_format: "MCP tool calls over stdio",
    output_format: "MCP tool results",
    rate_limit: "YouTube fair use",
    pricing: "Free (MIT)",
  },

  /* ------------------------------------------- productivity, CRM & support */
  {
    slug: "todoist-rest-api",
    name: "Todoist REST API",
    category: "api",
    summary: "Tasks, projects, labels and comments over a clean REST interface.",
    endpoint: "https://api.todoist.com/rest/v2/tasks",
    docs_url: "https://developer.todoist.com/rest/v2/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["productivity", "tasks"],
    capabilities: ["create task", "list tasks", "complete task", "manage projects"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "450 req / 15 min",
    pricing: "Free tier",
  },
  {
    slug: "clickup-api",
    name: "ClickUp",
    category: "api",
    summary: "Tasks, lists, docs and time tracking in one project-management API.",
    endpoint: "https://api.clickup.com/api/v2/list/<list_id>/task",
    docs_url: "https://developer.clickup.com/docs",
    auth_mode: "Authorization header (personal token)",
    auth_params: key("Authorization"),
    tags: ["productivity", "project-management"],
    capabilities: ["create task", "manage projects", "track time", "list tasks"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "100 req/min",
    pricing: "Free plan available",
  },
  {
    slug: "monday-api",
    name: "monday.com",
    category: "api",
    summary: "GraphQL API for boards, items, updates and automations.",
    endpoint: "https://api.monday.com/v2",
    docs_url: "https://developer.monday.com/api-reference/docs",
    auth_mode: "Authorization header (api token)",
    auth_params: key("Authorization"),
    tags: ["productivity", "project-management"],
    capabilities: ["create item", "manage boards", "project management", "update status"],
    input_format: "application/json (GraphQL)",
    output_format: "application/json",
    rate_limit: "Complexity budget per minute",
    pricing: "Plan dependent",
  },
  {
    slug: "trello-api",
    name: "Trello",
    category: "api",
    summary: "Boards, lists and cards for kanban workflows.",
    endpoint: "https://api.trello.com/1/cards",
    docs_url: "https://developer.atlassian.com/cloud/trello/rest/",
    auth_mode: "key + token query parameters",
    auth_params: [{ name: "key", location: "query", required: true }],
    tags: ["productivity", "project-management"],
    capabilities: ["create card", "manage boards", "list tasks", "project management"],
    input_format: "Query parameters or JSON",
    output_format: "application/json",
    rate_limit: "300 req / 10s per key",
    pricing: "Free plan available",
  },
  {
    slug: "microsoft-graph-api",
    name: "Microsoft Graph",
    category: "api",
    summary: "One endpoint for Outlook mail, calendar, Teams, OneDrive and users.",
    endpoint: "https://graph.microsoft.com/v1.0/me/messages",
    docs_url: "https://learn.microsoft.com/graph/api/overview",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["productivity", "email"],
    capabilities: ["send email", "read calendar", "create event", "list files", "post to teams"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Per-service throttling",
    pricing: "Included with Microsoft 365",
  },
  {
    slug: "google-tasks-api",
    name: "Google Tasks",
    category: "api",
    summary: "Task lists and tasks tied to a Google account.",
    endpoint: "https://tasks.googleapis.com/tasks/v1/lists/<list>/tasks",
    docs_url: "https://developers.google.com/tasks/reference/rest",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["productivity", "tasks"],
    capabilities: ["create task", "list tasks", "complete task"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Project quota",
    pricing: "Free",
  },
  {
    slug: "google-drive-api",
    name: "Google Drive",
    category: "api",
    summary: "Upload, search, share and export files in Drive.",
    endpoint: "https://www.googleapis.com/drive/v3/files",
    docs_url: "https://developers.google.com/drive/api/reference/rest/v3",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["storage", "files"],
    capabilities: ["upload file", "search files", "share file", "export document"],
    input_format: "application/json or multipart",
    output_format: "application/json",
    rate_limit: "12k req/min per project",
    pricing: "Free within Drive quota",
  },
  {
    slug: "dropbox-api",
    name: "Dropbox",
    category: "api",
    summary: "File upload, download, listing and sharing links.",
    endpoint: "https://api.dropboxapi.com/2/files/list_folder",
    docs_url: "https://www.dropbox.com/developers/documentation/http/documentation",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["storage", "files"],
    capabilities: ["upload file", "list files", "share file", "download file"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Per-app throttling",
    pricing: "Free tier",
  },
  {
    slug: "box-api",
    name: "Box",
    category: "api",
    summary: "Enterprise content management: files, folders, metadata and sign.",
    endpoint: "https://api.box.com/2.0/folders/0/items",
    docs_url: "https://developer.box.com/reference/",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["storage", "files"],
    capabilities: ["upload file", "list files", "share file", "manage metadata"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Free developer account",
  },
  {
    slug: "pipedrive-api",
    name: "Pipedrive",
    category: "api",
    summary: "CRM deals, persons, organisations and activities over REST.",
    endpoint: "https://api.pipedrive.com/v1/deals",
    docs_url: "https://developers.pipedrive.com/docs/api/v1",
    auth_mode: "api_token query parameter",
    auth_params: [{ name: "api_token", location: "query", required: true }],
    tags: ["crm", "sales"],
    capabilities: ["create deal", "manage contacts", "crm data", "log activity"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Token budget per 10s",
    pricing: "Plan dependent",
  },
  {
    slug: "zoho-crm-api",
    name: "Zoho CRM",
    category: "api",
    summary: "Leads, contacts, deals and custom modules in Zoho CRM.",
    endpoint: "https://www.zohoapis.com/crm/v6/Leads",
    docs_url: "https://www.zoho.com/crm/developer/docs/api/v6/",
    auth_mode: "Zoho-oauthtoken header",
    auth_params: key("Authorization"),
    tags: ["crm", "sales"],
    capabilities: ["create lead", "manage contacts", "crm data", "update deal"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Credit based per day",
    pricing: "Plan dependent",
  },
  {
    slug: "salesforce-rest-api",
    name: "Salesforce REST",
    category: "api",
    summary: "Query and mutate Salesforce objects with SOQL and sObject endpoints.",
    endpoint: "https://<instance>.my.salesforce.com/services/data/v60.0/sobjects/Account",
    docs_url: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/",
    auth_mode: "Bearer OAuth 2.0 token",
    auth_params: bearer,
    tags: ["crm", "sales"],
    capabilities: ["query crm", "create record", "manage contacts", "update deal"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Daily API call allowance",
    pricing: "Included with licence; free developer org",
  },
  {
    slug: "zendesk-api",
    name: "Zendesk Support",
    category: "api",
    summary: "Support tickets, users and comments over REST.",
    endpoint: "https://<subdomain>.zendesk.com/api/v2/tickets.json",
    docs_url: "https://developer.zendesk.com/api-reference/ticketing/introduction/",
    auth_mode: "HTTP Basic (email/token)",
    auth_params: key("Authorization"),
    tags: ["support", "tickets"],
    capabilities: ["create ticket", "list tickets", "reply to customer", "support workflow"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "700 req/min on Enterprise",
    pricing: "Plan dependent",
  },
  {
    slug: "freshdesk-api",
    name: "Freshdesk",
    category: "api",
    summary: "Helpdesk tickets, contacts and conversations over REST.",
    endpoint: "https://<domain>.freshdesk.com/api/v2/tickets",
    docs_url: "https://developers.freshdesk.com/api/",
    auth_mode: "HTTP Basic (api key)",
    auth_params: key("Authorization"),
    tags: ["support", "tickets"],
    capabilities: ["create ticket", "list tickets", "reply to customer", "support workflow"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent per minute",
    pricing: "Free plan available",
  },
  {
    slug: "cal-com-api",
    name: "Cal.com",
    category: "api",
    summary: "Open-source scheduling: event types, availability and bookings.",
    endpoint: "https://api.cal.com/v2/bookings",
    docs_url: "https://cal.com/docs/api-reference/v2/introduction",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["scheduling", "calendar"],
    capabilities: ["book meeting", "check availability", "manage calendar"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free self-hosted, hosted tiers",
  },
  {
    slug: "calendly-api",
    name: "Calendly",
    category: "api",
    summary: "Scheduled events, invitees and single-use booking links.",
    endpoint: "https://api.calendly.com/scheduled_events",
    docs_url: "https://developer.calendly.com/api-docs",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["scheduling", "calendar"],
    capabilities: ["book meeting", "list events", "manage calendar"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Tier dependent",
    pricing: "Free tier",
  },
  {
    slug: "typeform-api",
    name: "Typeform",
    category: "api",
    summary: "Create forms and read responses programmatically.",
    endpoint: "https://api.typeform.com/forms",
    docs_url: "https://www.typeform.com/developers/create/",
    auth_mode: "Bearer personal token",
    auth_params: bearer,
    tags: ["forms", "productivity"],
    capabilities: ["create form", "read responses", "collect data"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "2 req/s",
    pricing: "Free plan available",
  },
  {
    slug: "coda-api",
    name: "Coda",
    category: "api",
    summary: "Read and write docs, tables and rows in Coda.",
    endpoint: "https://coda.io/apis/v1/docs",
    docs_url: "https://coda.io/developers/apis/v1",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["documents", "productivity"],
    capabilities: ["read table", "write row", "manage documents"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Per-endpoint throttling",
    pricing: "Free tier",
  },
  {
    slug: "toggl-track-api",
    name: "Toggl Track",
    category: "api",
    summary: "Time entries, projects and reports for time tracking.",
    endpoint: "https://api.track.toggl.com/api/v9/me/time_entries",
    docs_url: "https://engineering.toggl.com/docs/",
    auth_mode: "HTTP Basic (api token)",
    auth_params: key("Authorization"),
    tags: ["productivity", "time-tracking"],
    capabilities: ["track time", "log time entry", "read reports"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1 req/s recommended",
    pricing: "Free tier",
  },
  {
    slug: "clockify-api",
    name: "Clockify",
    category: "api",
    summary: "Time tracking, timesheets and workspace reports over REST.",
    endpoint: "https://api.clockify.me/api/v1/workspaces",
    docs_url: "https://docs.clockify.me/",
    auth_mode: "X-Api-Key header",
    auth_params: key("X-Api-Key"),
    tags: ["productivity", "time-tracking"],
    capabilities: ["track time", "log time entry", "read reports"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "50 req/s",
    pricing: "Free plan available",
  },

  /* ------------------------------------------- infrastructure & data platforms */
  {
    slug: "upstash-redis-rest-api",
    name: "Upstash Redis REST",
    category: "api",
    summary: "Serverless Redis reachable over plain HTTPS — ideal from edge runtimes.",
    endpoint: "https://<endpoint>.upstash.io/set/<key>/<value>",
    docs_url: "https://upstash.com/docs/redis/features/restapi",
    auth_mode: "Bearer REST token",
    auth_params: bearer,
    tags: ["database", "cache"],
    capabilities: ["read cache", "write key", "rate limiting", "store state"],
    input_format: "Path parameters or JSON commands",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier 10k commands/day",
  },
  {
    slug: "turso-platform-api",
    name: "Turso Platform",
    category: "api",
    summary: "Create and manage SQLite (libSQL) databases at the edge via API.",
    endpoint: "https://api.turso.tech/v1/organizations/<org>/databases",
    docs_url: "https://docs.turso.tech/api-reference/introduction",
    auth_mode: "Bearer platform token",
    auth_params: bearer,
    tags: ["database", "infrastructure"],
    capabilities: ["create database", "manage database", "run sql"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier",
  },
  {
    slug: "backblaze-b2-api",
    name: "Backblaze B2",
    category: "api",
    summary: "Cheap object storage with a native API and S3-compatible endpoint.",
    endpoint: "https://api.backblazeb2.com/b2api/v3/b2_authorize_account",
    docs_url: "https://www.backblaze.com/apidocs/introduction-to-the-b2-native-api",
    auth_mode: "HTTP Basic then bearer token",
    auth_params: key("Authorization"),
    tags: ["storage", "infrastructure"],
    capabilities: ["upload file", "store object", "download file", "object storage"],
    input_format: "application/json or binary",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "10 GB free storage",
  },
  {
    slug: "minio-mc-cli",
    name: "MinIO Client (mc)",
    category: "cli",
    summary: "S3-compatible object storage client for copy, mirror and policy work.",
    endpoint: "mc cp file.txt myminio/bucket/",
    docs_url: "https://min.io/docs/minio/linux/reference/minio-mc.html",
    auth_mode: "Alias with access/secret key",
    tags: ["storage", "cli"],
    capabilities: ["upload file", "mirror bucket", "object storage", "manage policy"],
    input_format: "CLI arguments",
    output_format: "Text / JSON on stdout",
    rate_limit: "Local / server bound",
    pricing: "Free (AGPL)",
  },
  {
    slug: "fly-io-machines-api",
    name: "Fly.io Machines",
    category: "api",
    summary: "Start, stop and inspect Firecracker VMs across regions over REST.",
    endpoint: "https://api.machines.dev/v1/apps/<app>/machines",
    docs_url: "https://fly.io/docs/machines/api/",
    auth_mode: "Bearer Fly API token",
    auth_params: bearer,
    tags: ["infrastructure", "compute"],
    capabilities: ["start vm", "stop vm", "deploy app", "cloud operations"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Pay per second of compute",
  },
  {
    slug: "render-api",
    name: "Render",
    category: "api",
    summary: "Manage services, deploys, env vars and logs on Render.",
    endpoint: "https://api.render.com/v1/services",
    docs_url: "https://api-docs.render.com/reference/introduction",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["infrastructure", "deployment"],
    capabilities: ["deploy app", "manage services", "read logs", "cloud operations"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Free instance tier",
  },
  {
    slug: "digitalocean-api",
    name: "DigitalOcean",
    category: "api",
    summary: "Droplets, databases, App Platform and Spaces over one REST API.",
    endpoint: "https://api.digitalocean.com/v2/droplets",
    docs_url: "https://docs.digitalocean.com/reference/api/",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["infrastructure", "cloud"],
    capabilities: ["create server", "manage infrastructure", "deploy app", "cloud operations"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "5,000 req/hour",
    pricing: "Pay per resource",
  },
  {
    slug: "hetzner-cloud-api",
    name: "Hetzner Cloud",
    category: "api",
    summary: "Provision servers, volumes, networks and firewalls via REST.",
    endpoint: "https://api.hetzner.cloud/v1/servers",
    docs_url: "https://docs.hetzner.cloud/",
    auth_mode: "Bearer project token",
    auth_params: bearer,
    tags: ["infrastructure", "cloud"],
    capabilities: ["create server", "manage infrastructure", "cloud operations"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "3,600 req/hour",
    pricing: "Pay per hour",
  },
  {
    slug: "linode-api",
    name: "Akamai Linode",
    category: "api",
    summary: "Instances, LKE clusters, object storage and DNS over REST.",
    endpoint: "https://api.linode.com/v4/linode/instances",
    docs_url: "https://techdocs.akamai.com/linode-api/reference/api",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["infrastructure", "cloud"],
    capabilities: ["create server", "manage infrastructure", "manage dns", "cloud operations"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Endpoint dependent",
    pricing: "Pay per hour",
  },
  {
    slug: "desec-dns-api",
    name: "deSEC DNS",
    category: "api",
    summary: "Free DNS hosting with a full REST API and DNSSEC by default.",
    endpoint: "https://desec.io/api/v1/domains/<domain>/rrsets/",
    docs_url: "https://desec.readthedocs.io/en/latest/",
    auth_mode: "Token header",
    auth_params: key("Authorization"),
    tags: ["dns", "infrastructure"],
    capabilities: ["manage dns", "create dns record", "dynamic dns"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Documented per-endpoint throttles",
    pricing: "Free (non-profit)",
  },
  {
    slug: "porkbun-api",
    name: "Porkbun",
    category: "api",
    summary: "Domain registration, DNS records and SSL bundles over JSON.",
    endpoint: "https://api.porkbun.com/api/json/v3/dns/retrieve/<domain>",
    docs_url: "https://porkbun.com/api/json/v3/documentation",
    auth_mode: "API key + secret in body",
    auth_params: [{ name: "apikey", location: "body", required: true }],
    tags: ["dns", "domains"],
    capabilities: ["manage dns", "check domain availability", "register domain"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free API, pay for domains",
  },
];
