import type { CatalogEntry } from "./catalog";

const bearer = [{ name: "Authorization", location: "header", required: true }];
const key = (name: string) => [{ name, location: "header", required: true }];
const basic = [{ name: "Authorization", location: "header", required: true }];
const none: { name: string; location: string; required: boolean }[] = [];

/**
 * Third bootstrap wave — breadth where agents actually ask.
 *
 * Driven by the need signals: messaging and notifications, documents and
 * conversion, company/legal/address data, geocoding and routing, weather and
 * environment, science and open data. No finance or market data by design.
 */
export const WAVE3_CATALOG: CatalogEntry[] = [
  /* ------------------------------------------- messaging & notifications */
  {
    slug: "onesignal-api",
    name: "OneSignal",
    category: "api",
    summary: "Push notifications to web, iOS and Android devices from one REST call.",
    endpoint: "https://api.onesignal.com/notifications",
    docs_url: "https://documentation.onesignal.com/reference/create-notification",
    auth_mode: "Key API key header",
    auth_params: key("Authorization"),
    tags: ["push", "notifications"],
    capabilities: ["send push notification", "notify users", "mobile push", "web push"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier for unlimited web push",
  },
  {
    slug: "pushover-api",
    name: "Pushover",
    category: "api",
    summary: "One-call push notification to your own phone or desktop, no SDK needed.",
    endpoint: "https://api.pushover.net/1/messages.json",
    docs_url: "https://pushover.net/api",
    auth_mode: "Token in body",
    auth_params: [{ name: "token", location: "body", required: true }],
    tags: ["push", "notifications"],
    capabilities: ["send push notification", "alert a human", "notify me"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "10k messages/month per application",
    pricing: "One-off licence per platform",
    invocation_example:
      'curl -s -F token=$TOKEN -F user=$USER -F "message=build finished" https://api.pushover.net/1/messages.json',
  },
  {
    slug: "ntfy-api",
    name: "ntfy",
    category: "api",
    summary: "Publish/subscribe notifications over plain HTTP, no account for public topics.",
    endpoint: "https://ntfy.sh/<topic>",
    docs_url: "https://docs.ntfy.sh/publish/",
    auth_mode: "None for public topics",
    auth_params: none,
    tags: ["push", "notifications"],
    capabilities: ["send push notification", "notify a topic", "alert a human"],
    input_format: "text/plain or application/json",
    output_format: "application/json",
    rate_limit: "Fair-use on ntfy.sh",
    pricing: "Free, self-hostable (Apache-2.0)",
    invocation_example: 'curl -d "deploy done" https://ntfy.sh/my-agent-topic',
  },
  {
    slug: "novu-api",
    name: "Novu",
    category: "api",
    summary: "Notification orchestration: one trigger fans out to email, SMS, push and in-app.",
    endpoint: "https://api.novu.co/v1/events/trigger",
    docs_url: "https://docs.novu.co/api-reference/events/trigger-event",
    auth_mode: "ApiKey header",
    auth_params: key("Authorization"),
    tags: ["notifications", "messaging"],
    capabilities: ["send notification", "multi-channel messaging", "notification workflow"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier, open source core",
  },
  {
    slug: "courier-api",
    name: "Courier",
    category: "api",
    summary: "Single send API that routes a message to email, SMS, Slack or push per user preference.",
    endpoint: "https://api.courier.com/send",
    docs_url: "https://www.courier.com/docs/reference/send/message/",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["notifications", "messaging"],
    capabilities: ["send notification", "send email", "multi-channel messaging"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier 10k notifications/month",
  },
  {
    slug: "plivo-sms-api",
    name: "Plivo Messaging",
    category: "api",
    summary: "Send SMS and MMS worldwide over a REST endpoint with delivery callbacks.",
    endpoint: "https://api.plivo.com/v1/Account/<auth_id>/Message/",
    docs_url: "https://www.plivo.com/docs/sms/api/message",
    auth_mode: "HTTP Basic (auth id + token)",
    auth_params: basic,
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send text message", "messaging"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Per message",
  },
  {
    slug: "vonage-sms-api",
    name: "Vonage SMS",
    category: "api",
    summary: "Global SMS delivery with a simple JSON endpoint and per-country routing.",
    endpoint: "https://rest.nexmo.com/sms/json",
    docs_url: "https://developer.vonage.com/en/api/sms",
    auth_mode: "API key + secret in body",
    auth_params: [{ name: "api_key", location: "body", required: true }],
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send text message"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "30 req/s default",
    pricing: "Per message, trial credit",
  },
  {
    slug: "messagebird-api",
    name: "Bird (MessageBird)",
    category: "api",
    summary: "SMS, WhatsApp and voice messaging through one omnichannel REST API.",
    endpoint: "https://rest.messagebird.com/messages",
    docs_url: "https://docs.bird.com/api",
    auth_mode: "AccessKey header",
    auth_params: key("Authorization"),
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "whatsapp message", "send text message"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Per message",
  },
  {
    slug: "textbelt-api",
    name: "Textbelt",
    category: "api",
    summary: "Send one SMS with a single POST; a free test key needs no account.",
    endpoint: "https://textbelt.com/text",
    docs_url: "https://docs.textbelt.com/",
    auth_mode: "Key in body (free 'textbelt' test key)",
    auth_params: [{ name: "key", location: "body", required: true }],
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send text message"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "1 free SMS/day per IP with the test key",
    pricing: "Pay per credit",
    invocation_example:
      'curl -X POST https://textbelt.com/text --data-urlencode phone=+15551234567 --data-urlencode "message=hi" -d key=textbelt',
  },
  {
    slug: "telnyx-messaging-api",
    name: "Telnyx Messaging",
    category: "api",
    summary: "Carrier-grade SMS/MMS over a REST API with number provisioning included.",
    endpoint: "https://api.telnyx.com/v2/messages",
    docs_url: "https://developers.telnyx.com/api/messaging/send-message",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send text message", "messaging"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Per message",
  },
  {
    slug: "clicksend-api",
    name: "ClickSend",
    category: "api",
    summary: "SMS, voice, fax and postal letters from one REST API.",
    endpoint: "https://rest.clicksend.com/v3/sms/send",
    docs_url: "https://developers.clicksend.com/docs/rest/v3/",
    auth_mode: "HTTP Basic",
    auth_params: basic,
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send letter", "send fax"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Per message",
  },
  {
    slug: "smtp2go-api",
    name: "SMTP2GO",
    category: "api",
    summary: "Transactional email over a JSON endpoint or plain SMTP relay.",
    endpoint: "https://api.smtp2go.com/v3/email/send",
    docs_url: "https://apidoc.smtp2go.com/documentation/",
    auth_mode: "API key header",
    auth_params: key("X-Smtp2go-Api-Key"),
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email", "smtp relay"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "1k emails/month free",
  },
  {
    slug: "mailersend-api",
    name: "MailerSend",
    category: "api",
    summary: "Transactional email and templates with a clean REST contract.",
    endpoint: "https://api.mailersend.com/v1/email",
    docs_url: "https://developers.mailersend.com/api/v1/email.html",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email", "email templates"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "10 req/min on trial",
    pricing: "3k emails/month free",
  },
  {
    slug: "zeptomail-api",
    name: "ZeptoMail",
    category: "api",
    summary: "Zoho's transactional-only email API, built for receipts and alerts.",
    endpoint: "https://api.zeptomail.com/v1.1/email",
    docs_url: "https://www.zoho.com/zeptomail/help/api/email-sending.html",
    auth_mode: "Zoho-enczapikey header",
    auth_params: key("Authorization"),
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Credit based, cheap tier",
  },
  {
    slug: "sparkpost-api",
    name: "SparkPost",
    category: "api",
    summary: "High-volume transactional email with engagement and deliverability data.",
    endpoint: "https://api.sparkpost.com/api/v1/transmissions",
    docs_url: "https://developers.sparkpost.com/api/transmissions/",
    auth_mode: "API key header",
    auth_params: key("Authorization"),
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email", "bulk email"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free developer tier",
  },
  {
    slug: "elasticemail-api",
    name: "Elastic Email",
    category: "api",
    summary: "Email sending and contact lists over a simple REST API.",
    endpoint: "https://api.elasticemail.com/v4/emails",
    docs_url: "https://elasticemail.com/developers/api-documentation/rest-api",
    auth_mode: "X-ElasticEmail-ApiKey header",
    auth_params: key("X-ElasticEmail-ApiKey"),
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email", "bulk email"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free 100 emails/day",
  },
  {
    slug: "mailtrap-api",
    name: "Mailtrap",
    category: "api",
    summary: "Safe email sandbox plus a sending API: test messages without reaching real inboxes.",
    endpoint: "https://send.api.mailtrap.io/api/send",
    docs_url: "https://api-docs.mailtrap.io/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["email", "testing"],
    capabilities: ["send email", "test email", "email sandbox"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free sandbox tier",
  },
  {
    slug: "matrix-client-api",
    name: "Matrix Client-Server API",
    category: "api",
    summary: "Send and read messages on any Matrix homeserver over an open federated protocol.",
    endpoint: "https://matrix.org/_matrix/client/v3/rooms/<roomId>/send/m.room.message",
    docs_url: "https://spec.matrix.org/latest/client-server-api/",
    auth_mode: "Bearer access token",
    auth_params: bearer,
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "read chat room", "team chat"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Homeserver dependent",
    pricing: "Free, open protocol",
  },
  {
    slug: "zulip-api",
    name: "Zulip",
    category: "api",
    summary: "Threaded team chat with a documented REST API for bots and agents.",
    endpoint: "https://<subdomain>.zulipchat.com/api/v1/messages",
    docs_url: "https://zulip.com/api/send-message",
    auth_mode: "HTTP Basic (bot email + key)",
    auth_params: basic,
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "team chat", "post to channel"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "Server configured",
    pricing: "Free for open-source/self-hosted",
  },
  {
    slug: "mattermost-api",
    name: "Mattermost",
    category: "api",
    summary: "Self-hostable team chat with a full REST API for posts, channels and users.",
    endpoint: "https://<server>/api/v4/posts",
    docs_url: "https://api.mattermost.com/",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "team chat", "post to channel"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Server configured",
    pricing: "Free self-hosted edition",
  },
  {
    slug: "rocketchat-api",
    name: "Rocket.Chat",
    category: "api",
    summary: "Open-source team chat REST API for messages, channels and webhooks.",
    endpoint: "https://<server>/api/v1/chat.postMessage",
    docs_url: "https://developer.rocket.chat/apidocs",
    auth_mode: "X-Auth-Token + X-User-Id headers",
    auth_params: key("X-Auth-Token"),
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "team chat", "post to channel"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Server configured",
    pricing: "Free self-hosted",
  },
  {
    slug: "line-messaging-api",
    name: "LINE Messaging",
    category: "api",
    summary: "Push messages to LINE users and groups, dominant in Japan and Taiwan.",
    endpoint: "https://api.line.me/v2/bot/message/push",
    docs_url: "https://developers.line.biz/en/reference/messaging-api/",
    auth_mode: "Bearer channel access token",
    auth_params: bearer,
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "messaging", "chatbot"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "2,000 req/s",
    pricing: "Free monthly message quota",
  },
  {
    slug: "viber-bot-api",
    name: "Viber Bot",
    category: "api",
    summary: "Send bot messages to Viber users over a single JSON endpoint.",
    endpoint: "https://chatapi.viber.com/pa/send_message",
    docs_url: "https://developers.viber.com/docs/api/rest-bot-api/",
    auth_mode: "X-Viber-Auth-Token header",
    auth_params: key("X-Viber-Auth-Token"),
    tags: ["chat", "messaging"],
    capabilities: ["send chat message", "chatbot", "messaging"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Account dependent",
    pricing: "Free for bots",
  },
  {
    slug: "svix-api",
    name: "Svix",
    category: "api",
    summary: "Outbound webhooks as a service: signing, retries and delivery logs.",
    endpoint: "https://api.svix.com/api/v1/app/<app_id>/msg/",
    docs_url: "https://api.svix.com/docs",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["webhooks", "messaging"],
    capabilities: ["send webhook", "webhook delivery", "event fan-out"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free tier, open source core",
  },
  {
    slug: "hookdeck-api",
    name: "Hookdeck",
    category: "api",
    summary: "Inbound webhook gateway with queuing, replay and inspection.",
    endpoint: "https://api.hookdeck.com/2025-01-01/events",
    docs_url: "https://hookdeck.com/docs/api",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["webhooks", "observability"],
    capabilities: ["receive webhook", "replay webhook", "inspect events"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free developer tier",
  },
  {
    slug: "webhook-site-api",
    name: "Webhook.site",
    category: "api",
    summary: "Disposable endpoint that captures any request so an agent can inspect callbacks.",
    endpoint: "https://webhook.site/token",
    docs_url: "https://docs.webhook.site/api/tokens.html",
    auth_mode: "None for temporary tokens",
    auth_params: none,
    tags: ["webhooks", "testing"],
    capabilities: ["capture webhook", "inspect request", "test callback"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free tier",
    invocation_example: "curl -X POST https://webhook.site/token",
  },

  /* ------------------------------------------- documents & conversion */
  {
    slug: "gotenberg-api",
    name: "Gotenberg",
    category: "api",
    summary: "Self-hosted HTTP service that converts HTML, Markdown and Office files to PDF.",
    endpoint: "http://<host>:3000/forms/chromium/convert/html",
    docs_url: "https://gotenberg.dev/docs/routes",
    auth_mode: "None (deploy behind your own gate)",
    auth_params: none,
    tags: ["documents", "pdf"],
    capabilities: ["html to pdf", "convert document", "generate pdf", "office to pdf"],
    input_format: "multipart/form-data",
    output_format: "application/pdf",
    rate_limit: "Self-hosted",
    pricing: "Free (MIT)",
  },
  {
    slug: "pdfshift-api",
    name: "PDFShift",
    category: "api",
    summary: "Turn a URL or raw HTML into a PDF with one authenticated POST.",
    endpoint: "https://api.pdfshift.io/v3/convert/pdf",
    docs_url: "https://docs.pdfshift.io/",
    auth_mode: "HTTP Basic (api key)",
    auth_params: basic,
    tags: ["documents", "pdf"],
    capabilities: ["html to pdf", "url to pdf", "generate pdf"],
    input_format: "application/json",
    output_format: "application/pdf",
    rate_limit: "Plan dependent",
    pricing: "50 free conversions/month",
  },
  {
    slug: "api2pdf-api",
    name: "Api2Pdf",
    category: "api",
    summary: "PDF generation and merging across Chrome, LibreOffice and wkhtmltopdf engines.",
    endpoint: "https://v2.api2pdf.com/chrome/pdf/url",
    docs_url: "https://www.api2pdf.com/documentation/v2/",
    auth_mode: "Authorization header (api key)",
    auth_params: key("Authorization"),
    tags: ["documents", "pdf"],
    capabilities: ["html to pdf", "merge pdf", "office to pdf", "generate pdf"],
    input_format: "application/json",
    output_format: "application/json (PDF url)",
    rate_limit: "Plan dependent",
    pricing: "Pay per use",
  },
  {
    slug: "ilovepdf-api",
    name: "iLovePDF",
    category: "api",
    summary: "PDF toolbox API: merge, split, compress, OCR, watermark, convert.",
    endpoint: "https://api.ilovepdf.com/v1/start/<tool>",
    docs_url: "https://developer.ilovepdf.com/docs",
    auth_mode: "Bearer JWT from project key",
    auth_params: bearer,
    tags: ["documents", "pdf"],
    capabilities: ["merge pdf", "split pdf", "compress pdf", "ocr pdf", "convert document"],
    input_format: "multipart/form-data",
    output_format: "application/pdf",
    rate_limit: "Plan dependent",
    pricing: "250 free files/month",
  },
  {
    slug: "ocr-space-api",
    name: "OCR.space",
    category: "api",
    summary: "Free-tier OCR endpoint that extracts text from images and PDFs in 20+ languages.",
    endpoint: "https://api.ocr.space/parse/image",
    docs_url: "https://ocr.space/ocrapi",
    auth_mode: "apikey header",
    auth_params: key("apikey"),
    tags: ["ocr", "documents"],
    capabilities: ["ocr image", "extract text", "pdf to text", "read scanned document"],
    input_format: "multipart/form-data or URL",
    output_format: "application/json",
    rate_limit: "25k requests/month on the free key",
    pricing: "Free tier, paid plans",
    invocation_example:
      'curl -X POST https://api.ocr.space/parse/image -H "apikey: $OCR_KEY" -F "url=https://example.com/scan.png"',
  },
  {
    slug: "mindee-api",
    name: "Mindee",
    category: "api",
    summary: "Document parsing for invoices, receipts and IDs with structured field output.",
    endpoint: "https://api.mindee.net/v1/products/mindee/invoices/v4/predict",
    docs_url: "https://developers.mindee.com/docs",
    auth_mode: "Token API key header",
    auth_params: key("Authorization"),
    tags: ["ocr", "documents"],
    capabilities: ["parse document", "extract fields", "read receipt", "ocr image"],
    input_format: "multipart/form-data",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "250 free pages/month",
  },
  {
    slug: "google-cloud-vision-api",
    name: "Google Cloud Vision",
    category: "api",
    summary: "OCR, label detection and document text extraction from images.",
    endpoint: "https://vision.googleapis.com/v1/images:annotate",
    docs_url: "https://cloud.google.com/vision/docs/reference/rest",
    auth_mode: "Bearer OAuth token or API key",
    auth_params: bearer,
    tags: ["ocr", "images"],
    capabilities: ["ocr image", "extract text", "detect labels", "read document"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1,800 req/min default",
    pricing: "1k units/month free",
  },
  {
    slug: "azure-document-intelligence-api",
    name: "Azure AI Document Intelligence",
    category: "api",
    summary: "Layout-aware document extraction: tables, key-value pairs, forms and handwriting.",
    endpoint: "https://<resource>.cognitiveservices.azure.com/documentintelligence/documentModels/prebuilt-layout:analyze",
    docs_url: "https://learn.microsoft.com/azure/ai-services/document-intelligence/",
    auth_mode: "Ocp-Apim-Subscription-Key header",
    auth_params: key("Ocp-Apim-Subscription-Key"),
    tags: ["ocr", "documents"],
    capabilities: ["parse document", "extract tables", "ocr image", "read pdf layout"],
    input_format: "application/json or binary",
    output_format: "application/json",
    rate_limit: "Tier dependent",
    pricing: "Free tier 500 pages/month",
  },
  {
    slug: "apache-tika-api",
    name: "Apache Tika Server",
    category: "api",
    summary: "Extract text and metadata from a thousand file types over HTTP PUT.",
    endpoint: "http://<host>:9998/tika",
    docs_url: "https://cwiki.apache.org/confluence/display/TIKA/TikaServer",
    auth_mode: "None (self-hosted)",
    auth_params: none,
    tags: ["documents", "extraction"],
    capabilities: ["extract text", "parse document", "read metadata", "pdf to text"],
    input_format: "Binary document body",
    output_format: "text/plain or application/json",
    rate_limit: "Self-hosted",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "llamaparse-api",
    name: "LlamaParse",
    category: "api",
    summary: "Parses complex PDFs into clean Markdown for retrieval pipelines.",
    endpoint: "https://api.cloud.llamaindex.ai/api/parsing/upload",
    docs_url: "https://docs.cloud.llamaindex.ai/llamaparse/getting_started",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["documents", "rag"],
    capabilities: ["parse document", "pdf to markdown", "extract tables", "prepare rag corpus"],
    input_format: "multipart/form-data",
    output_format: "application/json / Markdown",
    rate_limit: "Plan dependent",
    pricing: "1k free pages/day",
  },
  {
    slug: "qpdf-cli",
    name: "qpdf",
    category: "cli",
    summary: "Structural PDF surgery: split, merge, rotate, decrypt, linearise.",
    endpoint: "qpdf [options] infile outfile",
    docs_url: "https://qpdf.readthedocs.io/",
    auth_mode: "None",
    tags: ["pdf", "documents"],
    capabilities: ["split pdf", "merge pdf", "rotate pdf", "decrypt pdf"],
    input_format: "CLI arguments + PDF files",
    output_format: "PDF files",
    rate_limit: "Local CPU bound",
    pricing: "Free (Apache-2.0)",
  },
  {
    slug: "poppler-pdftotext-cli",
    name: "pdftotext (Poppler)",
    category: "cli",
    summary: "Extract the text layer of a PDF locally, with layout preservation.",
    endpoint: "pdftotext [-layout] input.pdf output.txt",
    docs_url: "https://poppler.freedesktop.org/",
    auth_mode: "None",
    tags: ["pdf", "documents"],
    capabilities: ["pdf to text", "extract text", "read pdf"],
    input_format: "CLI arguments + PDF file",
    output_format: "Text file",
    rate_limit: "Local CPU bound",
    pricing: "Free (GPL)",
  },
  {
    slug: "ghostscript-cli",
    name: "Ghostscript",
    category: "cli",
    summary: "PostScript/PDF interpreter used to compress, convert and rasterise PDFs.",
    endpoint: "gs -sDEVICE=pdfwrite -o out.pdf in.pdf",
    docs_url: "https://ghostscript.readthedocs.io/",
    auth_mode: "None",
    tags: ["pdf", "documents"],
    capabilities: ["compress pdf", "convert pdf", "pdf to image", "rasterise pdf"],
    input_format: "CLI arguments + PDF/PS files",
    output_format: "PDF / image files",
    rate_limit: "Local CPU bound",
    pricing: "Free (AGPL)",
  },
  {
    slug: "libreoffice-cli",
    name: "LibreOffice (headless)",
    category: "cli",
    summary: "Convert Office documents to PDF, DOCX, XLSX or CSV without a GUI.",
    endpoint: "soffice --headless --convert-to pdf file.docx",
    docs_url: "https://help.libreoffice.org/latest/en-US/text/shared/guide/start_parameters.html",
    auth_mode: "None",
    tags: ["documents", "conversion"],
    capabilities: ["convert document", "docx to pdf", "xlsx to csv", "office to pdf"],
    input_format: "CLI arguments + document files",
    output_format: "Converted document files",
    rate_limit: "Local CPU bound",
    pricing: "Free (MPL-2.0)",
  },
  {
    slug: "ocrmypdf-cli",
    name: "OCRmyPDF",
    category: "cli",
    summary: "Adds a searchable text layer to scanned PDFs using Tesseract.",
    endpoint: "ocrmypdf input.pdf output.pdf",
    docs_url: "https://ocrmypdf.readthedocs.io/",
    auth_mode: "None",
    tags: ["ocr", "pdf"],
    capabilities: ["ocr pdf", "searchable pdf", "extract text"],
    input_format: "CLI arguments + PDF file",
    output_format: "PDF with text layer",
    rate_limit: "Local CPU bound",
    pricing: "Free (MPL-2.0)",
  },
  {
    slug: "markitdown-cli",
    name: "MarkItDown",
    category: "cli",
    summary: "Microsoft's converter turning PDF, Office, HTML and audio into Markdown for LLMs.",
    endpoint: "markitdown path/to/file.pdf > out.md",
    docs_url: "https://github.com/microsoft/markitdown",
    auth_mode: "None",
    tags: ["documents", "markdown"],
    capabilities: ["convert document", "pdf to markdown", "office to markdown", "prepare rag corpus"],
    input_format: "CLI arguments + document files",
    output_format: "Markdown on stdout",
    rate_limit: "Local CPU bound",
    pricing: "Free (MIT)",
  },
  {
    slug: "docling-cli",
    name: "Docling",
    category: "cli",
    summary: "IBM's document converter producing structured JSON/Markdown from PDFs and Office files.",
    endpoint: "docling path/to/file.pdf --to md",
    docs_url: "https://docling-project.github.io/docling/",
    auth_mode: "None",
    tags: ["documents", "markdown"],
    capabilities: ["convert document", "pdf to markdown", "extract tables", "parse document"],
    input_format: "CLI arguments + document files",
    output_format: "Markdown / JSON files",
    rate_limit: "Local CPU bound",
    pricing: "Free (MIT)",
  },

  /* ------------------------------------------- company, legal & address data */
  {
    slug: "ec-vies-vat-api",
    name: "EU VIES VAT validation",
    category: "api",
    summary: "Official EU service checking whether a VAT number is valid and to whom it belongs.",
    endpoint: "https://ec.europa.eu/taxation_customs/vies/rest-api/ms/<country>/vat/<number>",
    docs_url: "https://ec.europa.eu/taxation_customs/vies/#/technical-information",
    auth_mode: "None",
    auth_params: none,
    tags: ["company", "tax"],
    capabilities: ["validate vat number", "check company", "verify business identity"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Fair use, service windows apply",
    pricing: "Free (public service)",
    invocation_example:
      "curl https://ec.europa.eu/taxation_customs/vies/rest-api/ms/BE/vat/0123456789",
  },
  {
    slug: "gleif-lei-api",
    name: "GLEIF LEI",
    category: "api",
    summary: "Global legal-entity identifiers with official name, address and status.",
    endpoint: "https://api.gleif.org/api/v1/lei-records",
    docs_url: "https://www.gleif.org/en/lei-data/gleif-api",
    auth_mode: "None",
    auth_params: none,
    tags: ["company", "open-data"],
    capabilities: ["look up company", "legal entity identifier", "verify business identity"],
    input_format: "Query parameters",
    output_format: "application/vnd.api+json",
    rate_limit: "60 req/min",
    pricing: "Free (public data)",
  },
  {
    slug: "opencorporates-api",
    name: "OpenCorporates",
    category: "api",
    summary: "Company records aggregated from official registers worldwide.",
    endpoint: "https://api.opencorporates.com/v0.4/companies/search",
    docs_url: "https://api.opencorporates.com/documentation/API-Reference",
    auth_mode: "api_token query parameter",
    auth_params: [{ name: "api_token", location: "query", required: true }],
    tags: ["company", "open-data"],
    capabilities: ["look up company", "search companies", "verify business identity"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Plan dependent",
    pricing: "Free for public-benefit use",
  },
  {
    slug: "uk-companies-house-api",
    name: "UK Companies House",
    category: "api",
    summary: "Official UK register: company profiles, officers and filing history.",
    endpoint: "https://api.company-information.service.gov.uk/search/companies",
    docs_url: "https://developer-specs.company-information.service.gov.uk/",
    auth_mode: "HTTP Basic (api key as username)",
    auth_params: basic,
    tags: ["company", "open-data"],
    capabilities: ["look up company", "company officers", "filing history"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "600 requests / 5 min",
    pricing: "Free",
  },
  {
    slug: "insee-sirene-api",
    name: "INSEE Sirene",
    category: "api",
    summary: "French official registry of companies and establishments (SIREN/SIRET).",
    endpoint: "https://api.insee.fr/api-sirene/3.11/siren/<siren>",
    docs_url: "https://portail-api.insee.fr/",
    auth_mode: "X-INSEE-Api-Key-Integration header",
    auth_params: key("X-INSEE-Api-Key-Integration"),
    tags: ["company", "open-data"],
    capabilities: ["look up company", "siren lookup", "verify business identity"],
    input_format: "Path/query parameters",
    output_format: "application/json",
    rate_limit: "30 req/min",
    pricing: "Free with registration",
  },
  {
    slug: "recherche-entreprises-api",
    name: "Recherche d'entreprises (data.gouv.fr)",
    category: "api",
    summary: "Open French company search by name, SIREN or address, no key required.",
    endpoint: "https://recherche-entreprises.api.gouv.fr/search",
    docs_url: "https://recherche-entreprises.api.gouv.fr/docs/",
    auth_mode: "None",
    auth_params: none,
    tags: ["company", "open-data"],
    capabilities: ["look up company", "search companies", "siren lookup"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "7 req/s per IP",
    pricing: "Free (public service)",
    invocation_example: "curl 'https://recherche-entreprises.api.gouv.fr/search?q=airbus'",
  },
  {
    slug: "abstract-email-validation-api",
    name: "Abstract Email Validation",
    category: "api",
    summary: "Checks deliverability, syntax and disposable status of an email address.",
    endpoint: "https://emailvalidation.abstractapi.com/v1/",
    docs_url: "https://docs.abstractapi.com/email-validation",
    auth_mode: "api_key query parameter",
    auth_params: [{ name: "api_key", location: "query", required: true }],
    tags: ["email", "validation"],
    capabilities: ["validate email address", "check deliverability", "detect disposable email"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 req/s on free tier",
    pricing: "100 free requests/month",
  },
  {
    slug: "postcodes-io-api",
    name: "Postcodes.io",
    category: "api",
    summary: "UK postcode lookup and reverse geocoding, free and keyless.",
    endpoint: "https://api.postcodes.io/postcodes/<postcode>",
    docs_url: "https://postcodes.io/docs",
    auth_mode: "None",
    auth_params: none,
    tags: ["geocoding", "address"],
    capabilities: ["validate address", "postcode lookup", "reverse geocoding"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (open data)",
    invocation_example: "curl https://api.postcodes.io/postcodes/SW1A1AA",
  },
  {
    slug: "zippopotam-api",
    name: "Zippopotam.us",
    category: "api",
    summary: "Postal code to place name and coordinates for 60+ countries, no key.",
    endpoint: "https://api.zippopotam.us/<country>/<postalcode>",
    docs_url: "https://api.zippopotam.us/",
    auth_mode: "None",
    auth_params: none,
    tags: ["geocoding", "address"],
    capabilities: ["postcode lookup", "validate address", "geocoding"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free",
    invocation_example: "curl https://api.zippopotam.us/us/90210",
  },
  {
    slug: "opencage-geocoding-api",
    name: "OpenCage Geocoding",
    category: "api",
    summary: "Forward and reverse geocoding over open data with worldwide coverage.",
    endpoint: "https://api.opencagedata.com/geocode/v1/json",
    docs_url: "https://opencagedata.com/api",
    auth_mode: "key query parameter",
    auth_params: [{ name: "key", location: "query", required: true }],
    tags: ["geocoding", "maps"],
    capabilities: ["geocoding", "reverse geocoding", "address to coordinates"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 req/s on the free trial",
    pricing: "2,500 free requests/day trial",
  },
  {
    slug: "geoapify-geocoding-api",
    name: "Geoapify Geocoding",
    category: "api",
    summary: "Geocoding, autocomplete and places search built on OpenStreetMap data.",
    endpoint: "https://api.geoapify.com/v1/geocode/search",
    docs_url: "https://apidocs.geoapify.com/",
    auth_mode: "apiKey query parameter",
    auth_params: [{ name: "apiKey", location: "query", required: true }],
    tags: ["geocoding", "maps"],
    capabilities: ["geocoding", "address autocomplete", "places search"],
    input_format: "Query parameters",
    output_format: "application/json (GeoJSON)",
    rate_limit: "5 req/s free tier",
    pricing: "3,000 free requests/day",
  },
  {
    slug: "locationiq-api",
    name: "LocationIQ",
    category: "api",
    summary: "Nominatim-compatible geocoding and reverse geocoding with a generous free tier.",
    endpoint: "https://us1.locationiq.com/v1/search",
    docs_url: "https://docs.locationiq.com/",
    auth_mode: "key query parameter",
    auth_params: [{ name: "key", location: "query", required: true }],
    tags: ["geocoding", "maps"],
    capabilities: ["geocoding", "reverse geocoding", "address to coordinates"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "2 req/s free tier",
    pricing: "5,000 free requests/day",
  },
  {
    slug: "here-geocoding-api",
    name: "HERE Geocoding & Search",
    category: "api",
    summary: "Enterprise-grade geocoding, autosuggest and place lookup.",
    endpoint: "https://geocode.search.hereapi.com/v1/geocode",
    docs_url: "https://www.here.com/docs/bundle/geocoding-and-search-api-v7-api-reference",
    auth_mode: "apiKey query parameter",
    auth_params: [{ name: "apiKey", location: "query", required: true }],
    tags: ["geocoding", "maps"],
    capabilities: ["geocoding", "reverse geocoding", "places search"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "5 req/s free tier",
    pricing: "Free monthly allowance",
  },
  {
    slug: "bigdatacloud-reverse-geocode-api",
    name: "BigDataCloud Reverse Geocode",
    category: "api",
    summary: "Coordinates to locality, country and administrative divisions, free client tier.",
    endpoint: "https://api.bigdatacloud.net/data/reverse-geocode-client",
    docs_url: "https://www.bigdatacloud.com/docs/api/reverse-geocode-to-city-api",
    auth_mode: "None for the client endpoint",
    auth_params: none,
    tags: ["geocoding", "maps"],
    capabilities: ["reverse geocoding", "coordinates to city", "locate coordinates"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use on the client endpoint",
    pricing: "Free tier",
    invocation_example:
      "curl 'https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=48.85&longitude=2.35'",
  },

  /* ------------------------------------------- routing, transport, environment */
  {
    slug: "openrouteservice-api",
    name: "OpenRouteService",
    category: "api",
    summary: "Directions, isochrones and matrices for car, bike and foot over OSM data.",
    endpoint: "https://api.openrouteservice.org/v2/directions/driving-car",
    docs_url: "https://openrouteservice.org/dev/#/api-docs",
    auth_mode: "Authorization header (api key)",
    auth_params: key("Authorization"),
    tags: ["routing", "maps"],
    capabilities: ["route planning", "directions", "travel time matrix", "isochrones"],
    input_format: "application/json",
    output_format: "application/json (GeoJSON)",
    rate_limit: "2,000 requests/day free",
    pricing: "Free for fair use",
  },
  {
    slug: "osrm-routing-api",
    name: "OSRM demo server",
    category: "api",
    summary: "Fast car routing and travel-time matrices, keyless on the demo server.",
    endpoint: "https://router.project-osrm.org/route/v1/driving/<lon,lat>;<lon,lat>",
    docs_url: "http://project-osrm.org/docs/v5.24.0/api/",
    auth_mode: "None",
    auth_params: none,
    tags: ["routing", "maps"],
    capabilities: ["route planning", "directions", "travel time", "distance matrix"],
    input_format: "Path/query parameters",
    output_format: "application/json",
    rate_limit: "Demo server, fair use only",
    pricing: "Free (self-hostable, BSD)",
    invocation_example:
      "curl 'https://router.project-osrm.org/route/v1/driving/2.35,48.85;4.83,45.76?overview=false'",
  },
  {
    slug: "graphhopper-api",
    name: "GraphHopper",
    category: "api",
    summary: "Routing, map matching and route optimisation as a hosted API.",
    endpoint: "https://graphhopper.com/api/1/route",
    docs_url: "https://docs.graphhopper.com/",
    auth_mode: "key query parameter",
    auth_params: [{ name: "key", location: "query", required: true }],
    tags: ["routing", "maps"],
    capabilities: ["route planning", "directions", "route optimisation", "travel time"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Free tier limited daily credits",
    pricing: "Free developer tier",
  },
  {
    slug: "overpass-api",
    name: "Overpass API",
    category: "api",
    summary: "Query OpenStreetMap features by tag and area with the Overpass QL language.",
    endpoint: "https://overpass-api.de/api/interpreter",
    docs_url: "https://wiki.openstreetmap.org/wiki/Overpass_API",
    auth_mode: "None",
    auth_params: none,
    tags: ["maps", "open-data"],
    capabilities: ["query map data", "find places nearby", "extract osm features"],
    input_format: "Overpass QL in POST body",
    output_format: "application/json",
    rate_limit: "Shared instance, fair use",
    pricing: "Free (ODbL data)",
  },
  {
    slug: "db-transport-rest-api",
    name: "transport.rest (Deutsche Bahn)",
    category: "api",
    summary: "Keyless German rail departures, journeys and station search.",
    endpoint: "https://v6.db.transport.rest/journeys",
    docs_url: "https://v6.db.transport.rest/api.html",
    auth_mode: "None",
    auth_params: none,
    tags: ["transport", "travel"],
    capabilities: ["train timetable", "plan a journey", "departures board"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "100 req/min per IP",
    pricing: "Free (community service)",
    invocation_example: "curl 'https://v6.db.transport.rest/stations?query=Berlin'",
  },
  {
    slug: "navitia-api",
    name: "Navitia",
    category: "api",
    summary: "Multimodal public-transport journeys and schedules across many networks.",
    endpoint: "https://api.navitia.io/v1/coverage/<region>/journeys",
    docs_url: "https://doc.navitia.io/",
    auth_mode: "HTTP Basic (token as username)",
    auth_params: basic,
    tags: ["transport", "travel"],
    capabilities: ["plan a journey", "public transport schedule", "departures board"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Free tier limited",
    pricing: "Free developer tier",
  },
  {
    slug: "tfl-unified-api",
    name: "Transport for London Unified",
    category: "api",
    summary: "London transport status, journeys, stops and arrivals in real time.",
    endpoint: "https://api.tfl.gov.uk/Journey/JourneyResults/<from>/to/<to>",
    docs_url: "https://api-portal.tfl.gov.uk/api-details",
    auth_mode: "app_key query parameter (optional for low volume)",
    auth_params: [{ name: "app_key", location: "query", required: false }],
    tags: ["transport", "travel"],
    capabilities: ["plan a journey", "line status", "arrivals board"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "500 req/min with a key",
    pricing: "Free",
  },
  {
    slug: "opensky-network-api",
    name: "OpenSky Network",
    category: "api",
    summary: "Live and historical aircraft positions from a community ADS-B network.",
    endpoint: "https://opensky-network.org/api/states/all",
    docs_url: "https://openskynetwork.github.io/opensky-api/rest.html",
    auth_mode: "None (anonymous) or HTTP Basic",
    auth_params: none,
    tags: ["aviation", "open-data"],
    capabilities: ["track aircraft", "flight positions", "airspace data"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "400 credits/day anonymous",
    pricing: "Free for non-commercial use",
    invocation_example: "curl 'https://opensky-network.org/api/states/all?lamin=45&lomin=5&lamax=48&lomax=10'",
  },
  {
    slug: "open-elevation-api",
    name: "Open-Elevation",
    category: "api",
    summary: "Elevation for any coordinate pair, keyless and open source.",
    endpoint: "https://api.open-elevation.com/api/v1/lookup",
    docs_url: "https://open-elevation.com/",
    auth_mode: "None",
    auth_params: none,
    tags: ["geo", "open-data"],
    capabilities: ["elevation lookup", "terrain data", "coordinates to altitude"],
    input_format: "Query parameters or JSON",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (GPL, self-hostable)",
    invocation_example: "curl 'https://api.open-elevation.com/api/v1/lookup?locations=48.85,2.35'",
  },
  {
    slug: "open-topo-data-api",
    name: "Open Topo Data",
    category: "api",
    summary: "Elevation from multiple public DEM datasets over a keyless endpoint.",
    endpoint: "https://api.opentopodata.org/v1/<dataset>",
    docs_url: "https://www.opentopodata.org/api/",
    auth_mode: "None",
    auth_params: none,
    tags: ["geo", "open-data"],
    capabilities: ["elevation lookup", "terrain data"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 req/s, 1k calls/day on the public instance",
    pricing: "Free (MIT, self-hostable)",
  },
  {
    slug: "sunrise-sunset-api",
    name: "Sunrise-Sunset",
    category: "api",
    summary: "Sunrise, sunset, twilight and solar noon for any coordinates and date.",
    endpoint: "https://api.sunrise-sunset.org/json",
    docs_url: "https://sunrise-sunset.org/api",
    auth_mode: "None",
    auth_params: none,
    tags: ["weather", "open-data"],
    capabilities: ["sunrise sunset times", "daylight hours", "solar times"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free",
    invocation_example: "curl 'https://api.sunrise-sunset.org/json?lat=48.85&lng=2.35'",
  },
  {
    slug: "bright-sky-dwd-api",
    name: "Bright Sky (DWD)",
    category: "api",
    summary: "German weather service observations and forecasts as clean JSON, no key.",
    endpoint: "https://api.brightsky.dev/weather",
    docs_url: "https://brightsky.dev/docs/",
    auth_mode: "None",
    auth_params: none,
    tags: ["weather", "open-data"],
    capabilities: ["weather forecast", "current weather", "historical weather", "weather observations"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
    invocation_example: "curl 'https://api.brightsky.dev/current_weather?lat=52.52&lon=13.4'",
  },
  {
    slug: "meteostat-api",
    name: "Meteostat",
    category: "api",
    summary: "Historical weather and climate normals from thousands of stations.",
    endpoint: "https://meteostat.p.rapidapi.com/point/daily",
    docs_url: "https://dev.meteostat.net/api/",
    auth_mode: "RapidAPI key header",
    auth_params: key("X-RapidAPI-Key"),
    tags: ["weather", "open-data"],
    capabilities: ["historical weather", "climate data", "weather station data"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Free tier limited",
    pricing: "Free tier via RapidAPI",
  },
  {
    slug: "openaq-api",
    name: "OpenAQ",
    category: "api",
    summary: "Open air-quality measurements aggregated from public monitoring networks.",
    endpoint: "https://api.openaq.org/v3/locations",
    docs_url: "https://docs.openaq.org/",
    auth_mode: "X-API-Key header",
    auth_params: key("X-API-Key"),
    tags: ["environment", "open-data"],
    capabilities: ["air quality", "pollution data", "environmental measurements"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "60 req/min with a free key",
    pricing: "Free",
  },
  {
    slug: "waqi-air-quality-api",
    name: "World Air Quality Index",
    category: "api",
    summary: "Real-time air-quality index by city or coordinates.",
    endpoint: "https://api.waqi.info/feed/<city>/",
    docs_url: "https://aqicn.org/json-api/doc/",
    auth_mode: "token query parameter",
    auth_params: [{ name: "token", location: "query", required: true }],
    tags: ["environment", "open-data"],
    capabilities: ["air quality", "pollution data", "current aqi"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1,000 req/s burst limits apply",
    pricing: "Free token on request",
  },
  {
    slug: "noaa-tides-api",
    name: "NOAA Tides & Currents",
    category: "api",
    summary: "Official US tide predictions, water levels and currents.",
    endpoint: "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    docs_url: "https://api.tidesandcurrents.noaa.gov/api/prod/",
    auth_mode: "None",
    auth_params: none,
    tags: ["environment", "open-data"],
    capabilities: ["tide predictions", "water level", "marine data"],
    input_format: "Query parameters",
    output_format: "application/json or CSV",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
  {
    slug: "nasa-open-api",
    name: "NASA Open APIs",
    category: "api",
    summary: "NASA imagery, astronomy picture of the day, near-earth objects and Mars photos.",
    endpoint: "https://api.nasa.gov/planetary/apod",
    docs_url: "https://api.nasa.gov/",
    auth_mode: "api_key query parameter (DEMO_KEY works)",
    auth_params: [{ name: "api_key", location: "query", required: true }],
    tags: ["science", "open-data"],
    capabilities: ["space imagery", "astronomy data", "near earth objects"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "30 req/hour with DEMO_KEY, 1k/hour with a key",
    pricing: "Free",
    invocation_example: "curl 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY'",
  },

  /* ------------------------------------------- science & open data */
  {
    slug: "semantic-scholar-api",
    name: "Semantic Scholar",
    category: "api",
    summary: "Academic paper search, citations and references across 200M+ papers.",
    endpoint: "https://api.semanticscholar.org/graph/v1/paper/search",
    docs_url: "https://api.semanticscholar.org/api-docs/",
    auth_mode: "None (optional x-api-key for higher limits)",
    auth_params: none,
    tags: ["research", "open-data"],
    capabilities: ["search papers", "citation graph", "research a topic", "academic search"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "1 req/s unauthenticated",
    pricing: "Free",
    invocation_example:
      "curl 'https://api.semanticscholar.org/graph/v1/paper/search?query=agentic+ai&limit=3'",
  },
  {
    slug: "gbif-api",
    name: "GBIF",
    category: "api",
    summary: "Global biodiversity occurrence records and taxonomic backbone.",
    endpoint: "https://api.gbif.org/v1/occurrence/search",
    docs_url: "https://techdocs.gbif.org/en/openapi/",
    auth_mode: "None for reads",
    auth_params: none,
    tags: ["science", "open-data"],
    capabilities: ["species occurrence", "taxonomy lookup", "biodiversity data"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (open data)",
  },
  {
    slug: "inaturalist-api",
    name: "iNaturalist",
    category: "api",
    summary: "Species observations, identifications and taxa from a citizen-science network.",
    endpoint: "https://api.inaturalist.org/v1/observations",
    docs_url: "https://api.inaturalist.org/v1/docs/",
    auth_mode: "None for public reads",
    auth_params: none,
    tags: ["science", "open-data"],
    capabilities: ["species observation", "identify species", "biodiversity data"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "100 req/min, 10k/day",
    pricing: "Free",
  },
  {
    slug: "pubchem-api",
    name: "PubChem PUG REST",
    category: "api",
    summary: "Chemical compounds, properties and synonyms from NIH's PubChem.",
    endpoint: "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/<name>/JSON",
    docs_url: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
    auth_mode: "None",
    auth_params: none,
    tags: ["chemistry", "open-data"],
    capabilities: ["compound lookup", "chemical properties", "molecule data"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "5 req/s, 400 req/min",
    pricing: "Free (public data)",
    invocation_example: "curl https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/aspirin/JSON",
  },
  {
    slug: "chembl-api",
    name: "ChEMBL",
    category: "api",
    summary: "Bioactive molecules, targets and assay data from EMBL-EBI.",
    endpoint: "https://www.ebi.ac.uk/chembl/api/data/molecule",
    docs_url: "https://www.ebi.ac.uk/chembl/api/data/docs",
    auth_mode: "None",
    auth_params: none,
    tags: ["chemistry", "open-data"],
    capabilities: ["compound lookup", "drug data", "bioactivity data"],
    input_format: "Query parameters",
    output_format: "application/json or XML",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
  {
    slug: "uniprot-api",
    name: "UniProt",
    category: "api",
    summary: "Protein sequences and functional annotation, queryable and downloadable.",
    endpoint: "https://rest.uniprot.org/uniprotkb/search",
    docs_url: "https://www.uniprot.org/help/api_queries",
    auth_mode: "None",
    auth_params: none,
    tags: ["biology", "open-data"],
    capabilities: ["protein lookup", "sequence data", "biology data"],
    input_format: "Query parameters",
    output_format: "application/json, FASTA, TSV",
    rate_limit: "Fair use",
    pricing: "Free (CC-BY)",
  },
  {
    slug: "ensembl-rest-api",
    name: "Ensembl REST",
    category: "api",
    summary: "Genes, variants, sequences and comparative genomics across species.",
    endpoint: "https://rest.ensembl.org/lookup/symbol/homo_sapiens/<gene>",
    docs_url: "https://rest.ensembl.org/documentation",
    auth_mode: "None",
    auth_params: none,
    tags: ["biology", "open-data"],
    capabilities: ["gene lookup", "genome data", "variant data"],
    input_format: "Path/query parameters",
    output_format: "application/json",
    rate_limit: "15 req/s",
    pricing: "Free (public data)",
  },
  {
    slug: "rcsb-pdb-api",
    name: "RCSB Protein Data Bank",
    category: "api",
    summary: "3D structures of proteins and nucleic acids with search and metadata.",
    endpoint: "https://data.rcsb.org/rest/v1/core/entry/<pdbId>",
    docs_url: "https://data.rcsb.org/redoc/",
    auth_mode: "None",
    auth_params: none,
    tags: ["biology", "open-data"],
    capabilities: ["protein structure", "3d structure data", "biology data"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
  {
    slug: "datacite-api",
    name: "DataCite",
    category: "api",
    summary: "DOI metadata for research datasets, software and preprints.",
    endpoint: "https://api.datacite.org/dois",
    docs_url: "https://support.datacite.org/docs/api",
    auth_mode: "None for reads",
    auth_params: none,
    tags: ["research", "open-data"],
    capabilities: ["doi lookup", "dataset metadata", "academic search"],
    input_format: "Query parameters",
    output_format: "application/vnd.api+json",
    rate_limit: "Fair use",
    pricing: "Free",
  },
  {
    slug: "zenodo-api",
    name: "Zenodo",
    category: "api",
    summary: "Search and deposit open research records, datasets and software releases.",
    endpoint: "https://zenodo.org/api/records",
    docs_url: "https://developers.zenodo.org/",
    auth_mode: "None for search, token for deposit",
    auth_params: none,
    tags: ["research", "open-data"],
    capabilities: ["search datasets", "publish dataset", "doi lookup"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "60 req/min anonymous",
    pricing: "Free (CERN service)",
  },
  {
    slug: "orcid-public-api",
    name: "ORCID Public",
    category: "api",
    summary: "Researcher identifiers with affiliations and published works.",
    endpoint: "https://pub.orcid.org/v3.0/<orcid>/record",
    docs_url: "https://info.orcid.org/documentation/api-tutorials/",
    auth_mode: "None for the public API",
    auth_params: none,
    tags: ["research", "open-data"],
    capabilities: ["researcher lookup", "author identity", "academic search"],
    input_format: "Path parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free",
  },
  {
    slug: "who-gho-api",
    name: "WHO Global Health Observatory",
    category: "api",
    summary: "Official WHO health indicators by country and year over OData.",
    endpoint: "https://ghoapi.azureedge.net/api/<indicator>",
    docs_url: "https://www.who.int/data/gho/info/gho-odata-api",
    auth_mode: "None",
    auth_params: none,
    tags: ["health", "open-data"],
    capabilities: ["health statistics", "country indicators", "public health data"],
    input_format: "OData query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
  {
    slug: "eurostat-api",
    name: "Eurostat",
    category: "api",
    summary: "European statistics datasets in JSON-stat, filterable by dimension.",
    endpoint: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/<dataset>",
    docs_url: "https://wikis.ec.europa.eu/display/EUROSTATHELP/API+-+Getting+started",
    auth_mode: "None",
    auth_params: none,
    tags: ["statistics", "open-data"],
    capabilities: ["statistics data", "country indicators", "public dataset"],
    input_format: "Query parameters",
    output_format: "application/json (JSON-stat)",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
  {
    slug: "data-gouv-fr-api",
    name: "data.gouv.fr",
    category: "api",
    summary: "French open-data portal: search datasets, resources and organisations.",
    endpoint: "https://www.data.gouv.fr/api/1/datasets/",
    docs_url: "https://doc.data.gouv.fr/api/intro/",
    auth_mode: "None for reads",
    auth_params: none,
    tags: ["open-data", "statistics"],
    capabilities: ["search datasets", "public dataset", "open data search"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (public service)",
  },
  {
    slug: "ckan-data-gov-api",
    name: "data.gov (CKAN)",
    category: "api",
    summary: "US federal open-data catalogue searchable through the CKAN action API.",
    endpoint: "https://catalog.data.gov/api/3/action/package_search",
    docs_url: "https://docs.ckan.org/en/latest/api/",
    auth_mode: "None for reads",
    auth_params: none,
    tags: ["open-data", "statistics"],
    capabilities: ["search datasets", "public dataset", "open data search"],
    input_format: "Query parameters",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free (public data)",
  },
];
