import type { CatalogEntry } from "./catalog";

const bearer = [{ name: "Authorization", location: "header", required: true }];
const key = (name: string) => [{ name, location: "header", required: true }];
const none: { name: string; location: string; required: boolean }[] = [];

/**
 * Second bootstrap wave — coverage breadth.
 *
 * The first wave covered the interfaces every agent reaches for. This wave
 * closes the gaps the discovery engine kept reporting as uncovered: search,
 * scraping, geo, storage, observability, docs, media, finance, devops.
 */
export const EXTRA_CATALOG: CatalogEntry[] = [
  /* ---------------------------------------------------------------- APIs */
  {
    slug: "tavily-search-api",
    name: "Tavily Search",
    category: "api",
    summary: "Web search built for LLM consumption: ranked results with extracted page content.",
    endpoint: "https://api.tavily.com/search",
    docs_url: "https://docs.tavily.com/api-reference/endpoint/search",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["search", "web"],
    capabilities: ["web search", "search the internet", "research a topic", "extract page content"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "100 req/min",
    pricing: "1k credits/mo free",
    invocation_example:
      'curl -X POST https://api.tavily.com/search -H "Authorization: Bearer $TAVILY_API_KEY" -d \'{"query":"agentic web"}\'',
    verified: true,
  },
  {
    slug: "exa-search-api",
    name: "Exa",
    category: "api",
    summary: "Neural search over the web with semantic queries and full-text retrieval.",
    endpoint: "https://api.exa.ai/search",
    docs_url: "https://docs.exa.ai/reference/search",
    auth_mode: "x-api-key header",
    auth_params: key("x-api-key"),
    tags: ["search", "web"],
    capabilities: ["semantic search", "web search", "find similar pages", "retrieve page contents"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "5 req/s",
    pricing: "usage-based, free tier",
    invocation_example:
      'curl -X POST https://api.exa.ai/search -H "x-api-key: $EXA_API_KEY" -d \'{"query":"MCP registries","numResults":5}\'',
  },
  {
    slug: "firecrawl-api",
    name: "Firecrawl",
    category: "api",
    summary: "Turn any URL or whole site into clean markdown ready for a model context.",
    endpoint: "https://api.firecrawl.dev/v1/scrape",
    docs_url: "https://docs.firecrawl.dev/api-reference/endpoint/scrape",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["scraping", "web"],
    capabilities: ["scrape a website", "crawl a site", "html to markdown", "extract structured data"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "plan-based",
    pricing: "500 credits free",
    invocation_example:
      'curl -X POST https://api.firecrawl.dev/v1/scrape -H "Authorization: Bearer $FIRECRAWL_API_KEY" -d \'{"url":"https://example.com","formats":["markdown"]}\'',
    verified: true,
  },
  {
    slug: "browserless-api",
    name: "Browserless",
    category: "api",
    summary: "Headless Chrome as an HTTP service: screenshots, PDFs and full browser automation.",
    endpoint: "https://production-sfo.browserless.io/screenshot",
    docs_url: "https://docs.browserless.io/http-apis/screenshot",
    auth_mode: "token query parameter",
    auth_params: [{ name: "token", location: "query", required: true }],
    tags: ["browser", "automation"],
    capabilities: ["take a screenshot", "render a page", "generate a pdf", "browser automation"],
    input_format: "application/json",
    output_format: "image/png",
    rate_limit: "concurrency-based",
    pricing: "free trial, then usage",
    invocation_example:
      'curl -X POST "https://production-sfo.browserless.io/screenshot?token=$TOKEN" -d \'{"url":"https://example.com"}\' --output shot.png',
  },
  {
    slug: "deepl-api",
    name: "DeepL",
    category: "api",
    summary: "High-quality machine translation across 30+ languages with formality control.",
    endpoint: "https://api-free.deepl.com/v2/translate",
    docs_url: "https://developers.deepl.com/docs/api-reference/translate",
    auth_mode: "DeepL-Auth-Key header",
    auth_params: key("Authorization"),
    tags: ["translation", "language"],
    capabilities: ["translate text", "detect language", "translate a document"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "500k chars/mo free",
    pricing: "free tier then per character",
    invocation_example:
      'curl -X POST https://api-free.deepl.com/v2/translate -H "Authorization: DeepL-Auth-Key $DEEPL_KEY" -d "text=hello&target_lang=FR"',
  },
  {
    slug: "openweather-api",
    name: "OpenWeather",
    category: "api",
    summary: "Current conditions, forecasts and historical weather by coordinates or city.",
    endpoint: "https://api.openweathermap.org/data/2.5/weather",
    docs_url: "https://openweathermap.org/current",
    auth_mode: "appid query parameter",
    auth_params: [{ name: "appid", location: "query", required: true }],
    tags: ["weather", "geo"],
    capabilities: ["get the weather", "weather forecast", "historical weather"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "60 req/min free",
    pricing: "free tier",
    invocation_example:
      'curl "https://api.openweathermap.org/data/2.5/weather?q=Paris&appid=$OWM_KEY&units=metric"',
    verified: true,
  },
  {
    slug: "mapbox-geocoding-api",
    name: "Mapbox Geocoding",
    category: "api",
    summary: "Forward and reverse geocoding: addresses to coordinates and back.",
    endpoint: "https://api.mapbox.com/geocoding/v5/mapbox.places",
    docs_url: "https://docs.mapbox.com/api/search/geocoding/",
    auth_mode: "access_token query parameter",
    auth_params: [{ name: "access_token", location: "query", required: true }],
    tags: ["geo", "maps"],
    capabilities: ["geocode an address", "reverse geocode", "search places"],
    input_format: "query string",
    output_format: "application/geo+json",
    rate_limit: "600 req/min",
    pricing: "100k req/mo free",
    invocation_example:
      'curl "https://api.mapbox.com/geocoding/v5/mapbox.places/Paris.json?access_token=$MAPBOX_TOKEN"',
  },
  {
    slug: "twilio-messaging-api",
    name: "Twilio Messaging",
    category: "api",
    summary: "Send SMS, MMS and WhatsApp messages worldwide over a REST endpoint.",
    endpoint: "https://api.twilio.com/2010-04-01/Accounts/{AccountSid}/Messages.json",
    docs_url: "https://www.twilio.com/docs/messaging/api/message-resource",
    auth_mode: "HTTP Basic (SID + auth token)",
    auth_params: bearer,
    tags: ["sms", "messaging"],
    capabilities: ["send an sms", "send whatsapp message", "send a text message"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "1 msg/s per number",
    pricing: "per message",
    invocation_example:
      'curl -X POST "https://api.twilio.com/2010-04-01/Accounts/$SID/Messages.json" -u "$SID:$TOKEN" -d "To=+33...&From=+1...&Body=hi"',
    verified: true,
  },
  {
    slug: "slack-web-api",
    name: "Slack Web API",
    category: "api",
    summary: "Post messages, read channels and manage a workspace programmatically.",
    endpoint: "https://slack.com/api/chat.postMessage",
    docs_url: "https://api.slack.com/methods/chat.postMessage",
    auth_mode: "Bearer bot token",
    auth_params: bearer,
    tags: ["chat", "messaging"],
    capabilities: ["send a slack message", "post to a channel", "read channel history"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1 msg/s per channel",
    pricing: "free",
    invocation_example:
      'curl -X POST https://slack.com/api/chat.postMessage -H "Authorization: Bearer $SLACK_BOT_TOKEN" -d \'{"channel":"#general","text":"hi"}\'',
    verified: true,
  },
  {
    slug: "discord-api",
    name: "Discord REST API",
    category: "api",
    summary: "Bot-driven access to guilds, channels and messages.",
    endpoint: "https://discord.com/api/v10",
    docs_url: "https://discord.com/developers/docs/reference",
    auth_mode: "Bot token header",
    auth_params: bearer,
    tags: ["chat", "community"],
    capabilities: ["send a discord message", "manage channels", "read messages"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "dynamic per route",
    pricing: "free",
    invocation_example:
      'curl -X POST https://discord.com/api/v10/channels/$ID/messages -H "Authorization: Bot $TOKEN" -d \'{"content":"hi"}\'',
  },
  {
    slug: "cloudflare-r2-s3-api",
    name: "Cloudflare R2 (S3 API)",
    category: "api",
    summary: "S3-compatible object storage with zero egress fees.",
    endpoint: "https://{account}.r2.cloudflarestorage.com",
    docs_url: "https://developers.cloudflare.com/r2/api/s3/api/",
    auth_mode: "AWS SigV4",
    auth_params: key("Authorization"),
    tags: ["storage", "s3"],
    capabilities: ["store a file", "upload an object", "serve static assets", "object storage"],
    input_format: "binary",
    output_format: "binary / xml",
    rate_limit: "high",
    pricing: "10 GB/mo free",
    invocation_example: "aws s3 cp file.png s3://bucket/ --endpoint-url https://$ACCOUNT.r2.cloudflarestorage.com",
  },
  {
    slug: "algolia-search-api",
    name: "Algolia",
    category: "api",
    summary: "Hosted keyword and faceted search with sub-50ms responses.",
    endpoint: "https://{appid}-dsn.algolia.net/1/indexes/{index}/query",
    docs_url: "https://www.algolia.com/doc/rest-api/search/",
    auth_mode: "App ID + API key headers",
    auth_params: key("X-Algolia-API-Key"),
    tags: ["search", "index"],
    capabilities: ["full text search", "faceted search", "index documents", "autocomplete"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "plan-based",
    pricing: "10k searches/mo free",
    invocation_example:
      'curl -X POST "https://$APP-dsn.algolia.net/1/indexes/items/query" -H "X-Algolia-API-Key: $KEY" -H "X-Algolia-Application-Id: $APP" -d \'{"params":"query=shoes"}\'',
  },
  {
    slug: "pinecone-api",
    name: "Pinecone",
    category: "api",
    summary: "Managed vector database for embeddings, retrieval and RAG pipelines.",
    endpoint: "https://{index}-{project}.svc.{env}.pinecone.io/query",
    docs_url: "https://docs.pinecone.io/reference/api/introduction",
    auth_mode: "Api-Key header",
    auth_params: key("Api-Key"),
    tags: ["vector", "rag"],
    capabilities: ["vector search", "store embeddings", "semantic retrieval", "rag"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "plan-based",
    pricing: "free starter index",
    invocation_example:
      'curl -X POST "$PINECONE_HOST/query" -H "Api-Key: $PINECONE_API_KEY" -d \'{"vector":[0.1,0.2],"topK":5}\'',
  },
  {
    slug: "deepgram-api",
    name: "Deepgram",
    category: "api",
    summary: "Speech-to-text transcription with diarization, streaming and 30+ languages.",
    endpoint: "https://api.deepgram.com/v1/listen",
    docs_url: "https://developers.deepgram.com/reference/listen-remote-files",
    auth_mode: "Token header",
    auth_params: key("Authorization"),
    tags: ["audio", "speech"],
    capabilities: ["transcribe audio", "speech to text", "diarize speakers", "transcribe a call"],
    input_format: "audio/* or application/json",
    output_format: "application/json",
    rate_limit: "concurrency-based",
    pricing: "$200 free credit",
    invocation_example:
      'curl -X POST https://api.deepgram.com/v1/listen -H "Authorization: Token $DG_KEY" -d \'{"url":"https://x/audio.wav"}\'',
  },
  {
    slug: "elevenlabs-api",
    name: "ElevenLabs",
    category: "api",
    summary: "Text-to-speech with cloned and multilingual voices, streaming supported.",
    endpoint: "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
    docs_url: "https://elevenlabs.io/docs/api-reference/text-to-speech",
    auth_mode: "xi-api-key header",
    auth_params: key("xi-api-key"),
    tags: ["audio", "voice"],
    capabilities: ["text to speech", "generate a voice", "narrate text", "clone a voice"],
    input_format: "application/json",
    output_format: "audio/mpeg",
    rate_limit: "concurrency-based",
    pricing: "10k chars/mo free",
    invocation_example:
      'curl -X POST https://api.elevenlabs.io/v1/text-to-speech/$VOICE -H "xi-api-key: $KEY" -d \'{"text":"hello"}\' --output out.mp3',
  },
  {
    slug: "replicate-api",
    name: "Replicate",
    category: "api",
    summary: "Run thousands of open-source models (image, video, audio) behind one prediction API.",
    endpoint: "https://api.replicate.com/v1/predictions",
    docs_url: "https://replicate.com/docs/reference/http",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["models", "inference"],
    capabilities: ["generate an image", "run a model", "video generation", "upscale an image"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "600 req/min",
    pricing: "per second of compute",
    invocation_example:
      'curl -X POST https://api.replicate.com/v1/predictions -H "Authorization: Bearer $REPLICATE_TOKEN" -d \'{"version":"...","input":{"prompt":"a cat"}}\'',
    verified: true,
  },
  {
    slug: "sentry-api",
    name: "Sentry API",
    category: "api",
    summary: "Read issues, events and releases from an error-monitoring project.",
    endpoint: "https://sentry.io/api/0/projects/{org}/{project}/issues/",
    docs_url: "https://docs.sentry.io/api/",
    auth_mode: "Bearer auth token",
    auth_params: bearer,
    tags: ["observability", "errors"],
    capabilities: ["list errors", "read issues", "monitor exceptions", "triage a bug"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "org-based",
    pricing: "free tier",
    invocation_example:
      'curl "https://sentry.io/api/0/projects/$ORG/$PROJ/issues/" -H "Authorization: Bearer $SENTRY_TOKEN"',
  },
  {
    slug: "linear-graphql-api",
    name: "Linear GraphQL API",
    category: "api",
    summary: "Create, query and update issues, projects and cycles from a single GraphQL endpoint.",
    endpoint: "https://api.linear.app/graphql",
    docs_url: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
    auth_mode: "API key header",
    auth_params: key("Authorization"),
    tags: ["issues", "project-management"],
    capabilities: ["create an issue", "track a task", "query a backlog", "update project status"],
    input_format: "application/json (GraphQL)",
    output_format: "application/json",
    rate_limit: "1500 req/h",
    pricing: "free with workspace",
    invocation_example:
      'curl -X POST https://api.linear.app/graphql -H "Authorization: $LINEAR_KEY" -d \'{"query":"{ viewer { id } }"}\'',
    verified: true,
  },
  {
    slug: "notion-api",
    name: "Notion API",
    category: "api",
    summary: "Read and write pages, databases and blocks in a Notion workspace.",
    endpoint: "https://api.notion.com/v1",
    docs_url: "https://developers.notion.com/reference/intro",
    auth_mode: "Bearer integration token",
    auth_params: bearer,
    tags: ["docs", "knowledge"],
    capabilities: ["read a document", "write a page", "query a database", "store notes"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "3 req/s",
    pricing: "free",
    invocation_example:
      'curl https://api.notion.com/v1/pages/$ID -H "Authorization: Bearer $NOTION_KEY" -H "Notion-Version: 2022-06-28"',
  },
  {
    slug: "airtable-api",
    name: "Airtable",
    category: "api",
    summary: "Structured records over REST, useful as an agent-writable lightweight database.",
    endpoint: "https://api.airtable.com/v0/{baseId}/{table}",
    docs_url: "https://airtable.com/developers/web/api/introduction",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["database", "records"],
    capabilities: ["store records", "query a table", "update a row", "lightweight database"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "5 req/s per base",
    pricing: "free tier",
    invocation_example:
      'curl "https://api.airtable.com/v0/$BASE/Table" -H "Authorization: Bearer $AIRTABLE_PAT"',
  },
  {
    slug: "google-calendar-api",
    name: "Google Calendar API",
    category: "api",
    summary: "Create, list and update calendar events on behalf of a user.",
    endpoint: "https://www.googleapis.com/calendar/v3/calendars/{calendarId}/events",
    docs_url: "https://developers.google.com/calendar/api/v3/reference/events",
    auth_mode: "OAuth 2.0 bearer token",
    auth_params: bearer,
    tags: ["calendar", "scheduling"],
    capabilities: ["create an event", "schedule a meeting", "list events", "check availability"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1M queries/day",
    pricing: "free",
    invocation_example:
      'curl "https://www.googleapis.com/calendar/v3/calendars/primary/events" -H "Authorization: Bearer $TOKEN"',
  },
  {
    slug: "sec-edgar-api",
    name: "SEC EDGAR",
    category: "api",
    summary: "Public filings and company financial facts, no key required.",
    endpoint: "https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json",
    docs_url: "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
    auth_mode: "None (User-Agent header required)",
    auth_params: none,
    tags: ["finance", "open-data"],
    capabilities: ["company financials", "read sec filings", "public company data"],
    input_format: "path parameters",
    output_format: "application/json",
    rate_limit: "10 req/s",
    pricing: "free",
    invocation_example:
      'curl -H "User-Agent: agent@example.com" https://data.sec.gov/api/xbrl/companyfacts/CIK0000320193.json',
    verified: true,
  },
  {
    slug: "coingecko-api",
    name: "CoinGecko",
    category: "api",
    summary: "Crypto prices, market caps and historical charts, generous free tier.",
    endpoint: "https://api.coingecko.com/api/v3/simple/price",
    docs_url: "https://docs.coingecko.com/reference/introduction",
    auth_mode: "None (demo) / x-cg-api-key",
    auth_params: none,
    tags: ["crypto", "finance"],
    capabilities: ["crypto price", "market data", "historical prices"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "30 req/min free",
    pricing: "free tier",
    invocation_example:
      'curl "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"',
    verified: true,
  },
  {
    slug: "frankfurter-fx-api",
    name: "Frankfurter FX",
    category: "api",
    summary: "Reference exchange rates from the ECB, free and keyless.",
    endpoint: "https://api.frankfurter.app/latest",
    docs_url: "https://frankfurter.dev/",
    auth_mode: "None",
    auth_params: none,
    tags: ["finance", "open-data"],
    capabilities: ["convert currency", "exchange rate", "historical fx"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "fair use",
    pricing: "free",
    invocation_example: 'curl "https://api.frankfurter.app/latest?from=EUR&to=USD"',
    verified: true,
  },
  {
    slug: "wikipedia-api",
    name: "Wikipedia REST API",
    category: "api",
    summary: "Article summaries and full content, keyless and highly reliable.",
    endpoint: "https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
    docs_url: "https://en.wikipedia.org/api/rest_v1/",
    auth_mode: "None",
    auth_params: none,
    tags: ["knowledge", "open-data"],
    capabilities: ["look up a fact", "article summary", "encyclopedia lookup"],
    input_format: "path parameters",
    output_format: "application/json",
    rate_limit: "200 req/s",
    pricing: "free",
    invocation_example: "curl https://en.wikipedia.org/api/rest_v1/page/summary/Model_Context_Protocol",
    verified: true,
  },
  {
    slug: "unstructured-api",
    name: "Unstructured",
    category: "api",
    summary: "Parse PDFs, DOCX and slides into clean, chunked elements for retrieval.",
    endpoint: "https://api.unstructuredapp.io/general/v0/general",
    docs_url: "https://docs.unstructured.io/api-reference/api-services/overview",
    auth_mode: "unstructured-api-key header",
    auth_params: key("unstructured-api-key"),
    tags: ["documents", "parsing"],
    capabilities: ["parse a pdf", "extract text from a document", "chunk a document", "ocr"],
    input_format: "multipart/form-data",
    output_format: "application/json",
    rate_limit: "plan-based",
    pricing: "free tier",
    invocation_example:
      'curl -X POST https://api.unstructuredapp.io/general/v0/general -H "unstructured-api-key: $KEY" -F "files=@doc.pdf"',
  },
  {
    slug: "clearbit-logo-api",
    name: "Logo API (Clearbit)",
    category: "api",
    summary: "Company logo by domain, keyless image endpoint.",
    endpoint: "https://logo.clearbit.com/{domain}",
    docs_url: "https://clearbit.com/logo",
    auth_mode: "None",
    auth_params: none,
    tags: ["assets", "branding"],
    capabilities: ["get a company logo", "brand assets"],
    input_format: "path parameter",
    output_format: "image/png",
    rate_limit: "fair use",
    pricing: "free",
    invocation_example: "curl https://logo.clearbit.com/stripe.com --output logo.png",
  },
  {
    slug: "vercel-api",
    name: "Vercel REST API",
    category: "api",
    summary: "Trigger deployments, read logs and manage projects and domains.",
    endpoint: "https://api.vercel.com/v13/deployments",
    docs_url: "https://vercel.com/docs/rest-api",
    auth_mode: "Bearer token",
    auth_params: bearer,
    tags: ["deploy", "devops"],
    capabilities: ["deploy an app", "read deployment logs", "manage domains"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "plan-based",
    pricing: "free tier",
    invocation_example: 'curl https://api.vercel.com/v6/deployments -H "Authorization: Bearer $VERCEL_TOKEN"',
  },
  {
    slug: "cloudflare-api",
    name: "Cloudflare API",
    category: "api",
    summary: "DNS, Workers, caching and zone configuration over REST.",
    endpoint: "https://api.cloudflare.com/client/v4",
    docs_url: "https://developers.cloudflare.com/api/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["dns", "infrastructure"],
    capabilities: ["manage dns", "purge cache", "deploy a worker", "configure a domain"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1200 req/5min",
    pricing: "free tier",
    invocation_example:
      'curl "https://api.cloudflare.com/client/v4/zones" -H "Authorization: Bearer $CF_TOKEN"',
  },

  /* ---------------------------------------------------------------- MCPs */
  {
    slug: "playwright-mcp",
    name: "Playwright MCP",
    category: "mcp",
    summary: "Microsoft's official MCP server driving a real browser through accessibility snapshots.",
    endpoint: "npx @playwright/mcp@latest",
    docs_url: "https://github.com/microsoft/playwright-mcp",
    auth_mode: "None (local stdio)",
    auth_params: none,
    tags: ["browser", "automation"],
    capabilities: ["browse the web", "click elements", "fill a form", "take a screenshot", "e2e testing"],
    input_format: "MCP stdio",
    output_format: "MCP tool results",
    rate_limit: "local",
    pricing: "free / open source",
    invocation_example: '{"mcpServers":{"playwright":{"command":"npx","args":["@playwright/mcp@latest"]}}}',
    verified: true,
  },
  {
    slug: "filesystem-mcp",
    name: "Filesystem MCP",
    category: "mcp",
    summary: "Reference MCP server exposing sandboxed read/write access to local directories.",
    endpoint: "npx -y @modelcontextprotocol/server-filesystem /path",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    auth_mode: "None (path allow-list)",
    auth_params: none,
    tags: ["files", "local"],
    capabilities: ["read a file", "write a file", "list a directory", "search files"],
    input_format: "MCP stdio",
    output_format: "MCP tool results",
    rate_limit: "local",
    pricing: "free / open source",
    invocation_example:
      '{"mcpServers":{"filesystem":{"command":"npx","args":["-y","@modelcontextprotocol/server-filesystem","/work"]}}}',
    verified: true,
  },
  {
    slug: "fetch-mcp",
    name: "Fetch MCP",
    category: "mcp",
    summary: "Reference server that fetches a URL and converts it to markdown for the model.",
    endpoint: "uvx mcp-server-fetch",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    auth_mode: "None",
    auth_params: none,
    tags: ["web", "fetch"],
    capabilities: ["fetch a url", "read a web page", "html to markdown"],
    input_format: "MCP stdio",
    output_format: "MCP tool results",
    rate_limit: "local",
    pricing: "free / open source",
    invocation_example: '{"mcpServers":{"fetch":{"command":"uvx","args":["mcp-server-fetch"]}}}',
    verified: true,
  },
  {
    slug: "memory-mcp",
    name: "Memory MCP",
    category: "mcp",
    summary: "Knowledge-graph persistent memory across sessions, reference implementation.",
    endpoint: "npx -y @modelcontextprotocol/server-memory",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    auth_mode: "None",
    auth_params: none,
    tags: ["memory", "state"],
    capabilities: ["remember information", "persistent memory", "knowledge graph"],
    input_format: "MCP stdio",
    output_format: "MCP tool results",
    rate_limit: "local",
    pricing: "free / open source",
    invocation_example: '{"mcpServers":{"memory":{"command":"npx","args":["-y","@modelcontextprotocol/server-memory"]}}}',
  },
  {
    slug: "sequential-thinking-mcp",
    name: "Sequential Thinking MCP",
    category: "mcp",
    summary: "Structured step-by-step reasoning scaffold exposed as an MCP tool.",
    endpoint: "npx -y @modelcontextprotocol/server-sequential-thinking",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    auth_mode: "None",
    auth_params: none,
    tags: ["reasoning", "planning"],
    capabilities: ["plan a task", "structured reasoning", "decompose a problem"],
    input_format: "MCP stdio",
    output_format: "MCP tool results",
    rate_limit: "local",
    pricing: "free / open source",
    invocation_example:
      '{"mcpServers":{"sequential-thinking":{"command":"npx","args":["-y","@modelcontextprotocol/server-sequential-thinking"]}}}',
  },
  {
    slug: "notion-mcp",
    name: "Notion MCP",
    category: "mcp",
    summary: "Official hosted MCP server for reading and editing a Notion workspace.",
    endpoint: "https://mcp.notion.com/mcp",
    docs_url: "https://developers.notion.com/docs/mcp",
    auth_mode: "OAuth 2.1",
    auth_params: bearer,
    tags: ["docs", "knowledge"],
    capabilities: ["search notion", "create a page", "update a database", "read documents"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "workspace-based",
    pricing: "free with workspace",
    invocation_example: "claude mcp add --transport http notion https://mcp.notion.com/mcp",
    verified: true,
  },
  {
    slug: "linear-mcp",
    name: "Linear MCP",
    category: "mcp",
    summary: "Official hosted MCP server for issues, projects and cycles.",
    endpoint: "https://mcp.linear.app/mcp",
    docs_url: "https://linear.app/docs/mcp",
    auth_mode: "OAuth 2.1",
    auth_params: bearer,
    tags: ["issues", "project-management"],
    capabilities: ["create an issue", "search issues", "update a task", "read a project"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "workspace-based",
    pricing: "free with workspace",
    invocation_example: "claude mcp add --transport http linear https://mcp.linear.app/mcp",
    verified: true,
  },
  {
    slug: "sentry-mcp",
    name: "Sentry MCP",
    category: "mcp",
    summary: "Official hosted MCP server exposing issues, traces and Seer analysis.",
    endpoint: "https://mcp.sentry.dev/mcp",
    docs_url: "https://docs.sentry.io/product/sentry-mcp/",
    auth_mode: "OAuth 2.1",
    auth_params: bearer,
    tags: ["observability", "errors"],
    capabilities: ["read errors", "debug an issue", "search traces", "monitor a project"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "org-based",
    pricing: "free with account",
    invocation_example: "claude mcp add --transport http sentry https://mcp.sentry.dev/mcp",
    verified: true,
  },
  {
    slug: "hugging-face-mcp",
    name: "Hugging Face MCP",
    category: "mcp",
    summary: "Hosted MCP server over models, datasets, Spaces and inference.",
    endpoint: "https://huggingface.co/mcp",
    docs_url: "https://huggingface.co/settings/mcp",
    auth_mode: "Bearer HF token",
    auth_params: bearer,
    tags: ["models", "datasets"],
    capabilities: ["search models", "search datasets", "run inference", "explore spaces"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "account-based",
    pricing: "free tier",
    invocation_example: "claude mcp add --transport http huggingface https://huggingface.co/mcp",
  },
  {
    slug: "deepwiki-mcp",
    name: "DeepWiki MCP",
    category: "mcp",
    summary: "Ask questions about any public GitHub repository through generated documentation.",
    endpoint: "https://mcp.deepwiki.com/mcp",
    docs_url: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    auth_mode: "None (public)",
    auth_params: none,
    tags: ["code", "docs"],
    capabilities: ["understand a repository", "ask about a codebase", "read repo documentation"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "fair use",
    pricing: "free",
    invocation_example: "claude mcp add --transport http deepwiki https://mcp.deepwiki.com/mcp",
    verified: true,
  },
  {
    slug: "context7-mcp",
    name: "Context7 MCP",
    category: "mcp",
    summary: "Up-to-date library documentation injected into the model context on demand.",
    endpoint: "https://mcp.context7.com/mcp",
    docs_url: "https://github.com/upstash/context7",
    auth_mode: "Optional API key",
    auth_params: none,
    tags: ["docs", "libraries"],
    capabilities: ["read library docs", "up to date documentation", "resolve a package"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "fair use",
    pricing: "free tier",
    invocation_example: "claude mcp add --transport http context7 https://mcp.context7.com/mcp",
    verified: true,
  },
  {
    slug: "stripe-mcp",
    name: "Stripe MCP",
    category: "mcp",
    summary: "Official MCP server for customers, payments, subscriptions and Stripe docs.",
    endpoint: "https://mcp.stripe.com",
    docs_url: "https://docs.stripe.com/mcp",
    auth_mode: "OAuth 2.1 / restricted key",
    auth_params: bearer,
    tags: ["payments", "billing"],
    capabilities: ["create a customer", "issue a refund", "read payments", "manage subscriptions"],
    input_format: "MCP streamable http",
    output_format: "MCP tool results",
    rate_limit: "account-based",
    pricing: "free with account",
    invocation_example: "claude mcp add --transport http stripe https://mcp.stripe.com",
    verified: true,
  },
  {
    slug: "cloudflare-docs-mcp",
    name: "Cloudflare Docs MCP",
    category: "mcp",
    summary: "Hosted MCP server answering questions over the full Cloudflare documentation.",
    endpoint: "https://docs.mcp.cloudflare.com/sse",
    docs_url: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
    auth_mode: "None (public)",
    auth_params: none,
    tags: ["docs", "infrastructure"],
    capabilities: ["search documentation", "cloudflare help", "workers docs"],
    input_format: "MCP SSE",
    output_format: "MCP tool results",
    rate_limit: "fair use",
    pricing: "free",
    invocation_example: "claude mcp add --transport sse cloudflare-docs https://docs.mcp.cloudflare.com/sse",
  },

  /* ---------------------------------------------------------------- CLIs */
  {
    slug: "curl-cli",
    name: "curl",
    category: "cli",
    summary: "The universal HTTP client — the lowest common denominator for calling any interface.",
    endpoint: "curl",
    docs_url: "https://curl.se/docs/manpage.html",
    auth_mode: "Per-request headers",
    auth_params: none,
    tags: ["http", "core"],
    capabilities: ["call an api", "http request", "download a file", "post json"],
    input_format: "CLI flags",
    output_format: "stdout",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: 'curl -s -X POST https://api.example.com -H "Content-Type: application/json" -d \'{}\'',
    verified: true,
  },
  {
    slug: "jq-cli",
    name: "jq",
    category: "cli",
    summary: "Stream-oriented JSON processor — the glue between two API calls.",
    endpoint: "jq",
    docs_url: "https://jqlang.github.io/jq/manual/",
    auth_mode: "None",
    auth_params: none,
    tags: ["json", "core"],
    capabilities: ["parse json", "transform json", "filter data", "extract a field"],
    input_format: "stdin",
    output_format: "stdout",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "curl -s https://api.example.com | jq '.items[].id'",
    verified: true,
  },
  {
    slug: "ripgrep-cli",
    name: "ripgrep",
    category: "cli",
    summary: "Extremely fast recursive code and text search, respects .gitignore.",
    endpoint: "rg",
    docs_url: "https://github.com/BurntSushi/ripgrep",
    auth_mode: "None",
    auth_params: none,
    tags: ["search", "code"],
    capabilities: ["search a codebase", "find text in files", "grep"],
    input_format: "CLI args",
    output_format: "stdout",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "rg -n 'createServerFn' src/",
    verified: true,
  },
  {
    slug: "gh-cli",
    name: "GitHub CLI",
    category: "cli",
    summary: "Repos, issues, pull requests and Actions from the terminal, with auth built in.",
    endpoint: "gh",
    docs_url: "https://cli.github.com/manual/",
    auth_mode: "gh auth login / GH_TOKEN",
    auth_params: none,
    tags: ["git", "devops"],
    capabilities: ["open a pull request", "create an issue", "clone a repo", "run a workflow"],
    input_format: "CLI args",
    output_format: "stdout / json",
    rate_limit: "GitHub API limits",
    pricing: "free",
    invocation_example: 'gh pr create --title "fix" --body "..." --base main',
    verified: true,
  },
  {
    slug: "psql-cli",
    name: "psql",
    category: "cli",
    summary: "The PostgreSQL terminal client — direct SQL against any Postgres instance.",
    endpoint: "psql",
    docs_url: "https://www.postgresql.org/docs/current/app-psql.html",
    auth_mode: "Connection string",
    auth_params: none,
    tags: ["database", "sql"],
    capabilities: ["query postgres", "run sql", "inspect a schema", "export data"],
    input_format: "SQL",
    output_format: "stdout / csv",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: 'psql "$DATABASE_URL" -c "select count(*) from users;"',
    verified: true,
  },
  {
    slug: "duckdb-cli",
    name: "DuckDB CLI",
    category: "cli",
    summary: "In-process analytical SQL over CSV, Parquet and JSON without a server.",
    endpoint: "duckdb",
    docs_url: "https://duckdb.org/docs/stable/clients/cli/overview",
    auth_mode: "None",
    auth_params: none,
    tags: ["database", "analytics"],
    capabilities: ["analyze a csv", "query parquet", "run analytical sql", "data transformation"],
    input_format: "SQL",
    output_format: "stdout / parquet / json",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "duckdb -c \"select count(*) from read_csv_auto('data.csv')\"",
    verified: true,
  },
  {
    slug: "pandoc-cli",
    name: "Pandoc",
    category: "cli",
    summary: "Universal document converter between markdown, docx, HTML, PDF and more.",
    endpoint: "pandoc",
    docs_url: "https://pandoc.org/MANUAL.html",
    auth_mode: "None",
    auth_params: none,
    tags: ["documents", "conversion"],
    capabilities: ["convert a document", "markdown to pdf", "docx to markdown", "generate a report"],
    input_format: "files",
    output_format: "files",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "pandoc report.md -o report.pdf",
  },
  {
    slug: "imagemagick-cli",
    name: "ImageMagick",
    category: "cli",
    summary: "Resize, convert, composite and inspect images from the command line.",
    endpoint: "magick",
    docs_url: "https://imagemagick.org/script/command-line-processing.php",
    auth_mode: "None",
    auth_params: none,
    tags: ["images", "media"],
    capabilities: ["resize an image", "convert image format", "crop an image", "compress an image"],
    input_format: "image files",
    output_format: "image files",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "magick input.png -resize 800x600 output.jpg",
    verified: true,
  },
  {
    slug: "yt-dlp-cli",
    name: "yt-dlp",
    category: "cli",
    summary: "Download audio, video and subtitles from thousands of sites.",
    endpoint: "yt-dlp",
    docs_url: "https://github.com/yt-dlp/yt-dlp#usage-and-options",
    auth_mode: "Optional cookies",
    auth_params: none,
    tags: ["media", "download"],
    capabilities: ["download a video", "extract audio", "fetch subtitles", "get a transcript"],
    input_format: "URL",
    output_format: "media files",
    rate_limit: "site-based",
    pricing: "free / open source",
    invocation_example: "yt-dlp -x --audio-format mp3 https://example.com/video",
  },
  {
    slug: "docker-cli",
    name: "Docker CLI",
    category: "cli",
    summary: "Build, run and ship containers — the standard sandbox for agent-executed code.",
    endpoint: "docker",
    docs_url: "https://docs.docker.com/reference/cli/docker/",
    auth_mode: "docker login",
    auth_params: none,
    tags: ["containers", "devops"],
    capabilities: ["run code in a sandbox", "build an image", "deploy a container", "isolate execution"],
    input_format: "CLI args",
    output_format: "stdout",
    rate_limit: "registry limits",
    pricing: "free tier",
    invocation_example: "docker run --rm -v $PWD:/app python:3.12 python /app/script.py",
    verified: true,
  },
  {
    slug: "aws-cli",
    name: "AWS CLI",
    category: "cli",
    summary: "Full programmatic control of every AWS service from one binary.",
    endpoint: "aws",
    docs_url: "https://docs.aws.amazon.com/cli/latest/reference/",
    auth_mode: "IAM credentials / SSO",
    auth_params: none,
    tags: ["cloud", "devops"],
    capabilities: ["upload to s3", "manage cloud resources", "invoke a lambda", "provision infrastructure"],
    input_format: "CLI args",
    output_format: "json",
    rate_limit: "service-based",
    pricing: "free CLI, paid services",
    invocation_example: "aws s3 cp report.pdf s3://my-bucket/ --acl private",
  },
  {
    slug: "supabase-cli",
    name: "Supabase CLI",
    category: "cli",
    summary: "Migrations, local stack, type generation and deployments for a Postgres backend.",
    endpoint: "supabase",
    docs_url: "https://supabase.com/docs/reference/cli/introduction",
    auth_mode: "Access token",
    auth_params: none,
    tags: ["database", "backend"],
    capabilities: ["run a migration", "generate types", "start a local database", "deploy a function"],
    input_format: "CLI args",
    output_format: "stdout",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "supabase db push",
  },
  {
    slug: "openssl-cli",
    name: "OpenSSL",
    category: "cli",
    summary: "Hashing, signing, key generation and TLS inspection from the shell.",
    endpoint: "openssl",
    docs_url: "https://docs.openssl.org/master/man1/",
    auth_mode: "None",
    auth_params: none,
    tags: ["crypto", "security"],
    capabilities: ["hash a value", "generate a key", "sign data", "inspect a certificate"],
    input_format: "CLI args / stdin",
    output_format: "stdout",
    rate_limit: "none",
    pricing: "free / open source",
    invocation_example: "openssl rand -hex 32",
  },
];
