/**
 * Curated bootstrap catalog — the answer to the registry cold start.
 *
 * These are the interfaces agents actually reach for, described as machine
 * contracts (endpoint + auth + formats + limits) rather than marketing copy.
 * The ingest runner upserts them by slug, so this file is the source of truth:
 * editing an entry here and re-running the ingest updates the row in place.
 */

export type CatalogEntry = {
  slug: string;
  name: string;
  category: "api" | "mcp" | "cli";
  summary: string;
  description?: string;
  endpoint: string;
  docs_url?: string;
  auth_mode: string;
  auth_params?: { name: string; location: string; required: boolean }[];
  tags: string[];
  capabilities: string[];
  input_format?: string;
  output_format?: string;
  rate_limit?: string;
  pricing?: string;
  invocation_example?: string;
  verified?: boolean;
};

import { EXTRA_CATALOG } from "./catalog-extended";

const bearer = [{ name: "Authorization", location: "header", required: true }];
const apiKeyHeader = (name: string) => [{ name, location: "header", required: true }];

const BASE_CATALOG: CatalogEntry[] = [
  /* ---------------------------------------------------------------- APIs */
  {
    slug: "resend-api",
    name: "Resend",
    category: "api",
    summary: "Transactional email delivery over a single JSON endpoint, built for programmatic senders.",
    endpoint: "https://api.resend.com/emails",
    docs_url: "https://resend.com/docs/api-reference/emails/send-email",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["email", "messaging"],
    capabilities: ["send email", "transactional email", "email attachments", "batch email"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "2 req/s default",
    pricing: "3k emails/mo free, then usage-based",
    invocation_example:
      'curl -X POST https://api.resend.com/emails -H "Authorization: Bearer $RESEND_API_KEY" -H "Content-Type: application/json" -d \'{"from":"a@b.dev","to":"c@d.dev","subject":"hi","text":"hello"}\'',
    verified: true,
  },
  {
    slug: "stripe-api",
    name: "Stripe",
    category: "api",
    summary: "Payments, subscriptions, invoices and payouts over a stable REST contract.",
    endpoint: "https://api.stripe.com/v1",
    docs_url: "https://docs.stripe.com/api",
    auth_mode: "Bearer secret key",
    auth_params: bearer,
    tags: ["payments", "billing"],
    capabilities: ["charge card", "create subscription", "issue refund", "send invoice", "payment link"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "100 read/s, 100 write/s (live)",
    pricing: "Per transaction",
    invocation_example:
      'curl https://api.stripe.com/v1/payment_intents -u $STRIPE_KEY: -d amount=2000 -d currency=usd',
    verified: true,
  },
  {
    slug: "twilio-messaging-api",
    name: "Twilio Messaging",
    category: "api",
    summary: "Send and receive SMS, MMS and WhatsApp messages worldwide.",
    endpoint: "https://api.twilio.com/2010-04-01/Accounts",
    docs_url: "https://www.twilio.com/docs/messaging/api",
    auth_mode: "HTTP Basic (SID + token)",
    auth_params: [{ name: "Authorization", location: "header", required: true }],
    tags: ["sms", "messaging"],
    capabilities: ["send sms", "send whatsapp", "receive sms", "phone verification"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "Per-number throughput caps",
    pricing: "Per message",
    verified: true,
  },
  {
    slug: "openai-api",
    name: "OpenAI Platform",
    category: "api",
    summary: "Chat completions, embeddings, images, audio and structured outputs.",
    endpoint: "https://api.openai.com/v1",
    docs_url: "https://platform.openai.com/docs/api-reference",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["ai", "llm"],
    capabilities: ["chat completion", "text embedding", "generate image", "speech to text", "text to speech"],
    input_format: "application/json",
    output_format: "application/json or SSE stream",
    rate_limit: "Tier-based RPM/TPM",
    pricing: "Per token",
    verified: true,
  },
  {
    slug: "anthropic-api",
    name: "Anthropic Messages",
    category: "api",
    summary: "Claude models with tool use, long context and streaming responses.",
    endpoint: "https://api.anthropic.com/v1/messages",
    docs_url: "https://docs.anthropic.com/en/api/messages",
    auth_mode: "x-api-key header",
    auth_params: apiKeyHeader("x-api-key"),
    tags: ["ai", "llm"],
    capabilities: ["chat completion", "tool use", "long context reasoning", "vision"],
    input_format: "application/json",
    output_format: "application/json or SSE stream",
    rate_limit: "Tier-based RPM/TPM",
    pricing: "Per token",
    verified: true,
  },
  {
    slug: "brave-search-api",
    name: "Brave Search",
    category: "api",
    summary: "Independent web index queryable as JSON — a common grounding source for agents.",
    endpoint: "https://api.search.brave.com/res/v1/web/search",
    docs_url: "https://api-dashboard.search.brave.com/app/documentation",
    auth_mode: "X-Subscription-Token header",
    auth_params: apiKeyHeader("X-Subscription-Token"),
    tags: ["search", "web"],
    capabilities: ["web search", "news search", "ground answers"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "1 req/s free tier",
    pricing: "2k queries/mo free",
    verified: true,
  },
  {
    slug: "tavily-search-api",
    name: "Tavily",
    category: "api",
    summary: "Search API designed for LLM grounding: returns cleaned content, not link lists.",
    endpoint: "https://api.tavily.com/search",
    docs_url: "https://docs.tavily.com",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["search", "rag"],
    capabilities: ["web search", "extract page content", "research a topic"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan-based",
    pricing: "1k credits/mo free",
  },
  {
    slug: "firecrawl-api",
    name: "Firecrawl",
    category: "api",
    summary: "Turn any website into clean markdown or structured data for agent consumption.",
    endpoint: "https://api.firecrawl.dev/v1/scrape",
    docs_url: "https://docs.firecrawl.dev",
    auth_mode: "Bearer API key",
    auth_params: bearer,
    tags: ["scraping", "content"],
    capabilities: ["scrape website", "crawl site", "extract structured data", "html to markdown"],
    input_format: "application/json",
    output_format: "application/json (markdown payload)",
    rate_limit: "Plan-based",
    pricing: "Free tier then usage-based",
  },
  {
    slug: "github-rest-api",
    name: "GitHub REST",
    category: "api",
    summary: "Repositories, issues, pull requests, actions and releases as HTTP resources.",
    endpoint: "https://api.github.com",
    docs_url: "https://docs.github.com/en/rest",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["dev", "git"],
    capabilities: ["read repository", "open issue", "create pull request", "trigger workflow", "search code"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "5000 req/h authenticated",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "slack-web-api",
    name: "Slack Web API",
    category: "api",
    summary: "Post messages, manage channels and read conversations in a workspace.",
    endpoint: "https://slack.com/api",
    docs_url: "https://api.slack.com/web",
    auth_mode: "Bearer OAuth token",
    auth_params: bearer,
    tags: ["chat", "notifications"],
    capabilities: ["send chat message", "notify team", "read channel history", "upload file"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Tiered, ~1 msg/s per channel",
    pricing: "Free",
  },
  {
    slug: "notion-api",
    name: "Notion",
    category: "api",
    summary: "Read and write pages, databases and blocks in a Notion workspace.",
    endpoint: "https://api.notion.com/v1",
    docs_url: "https://developers.notion.com/reference",
    auth_mode: "Bearer integration token",
    auth_params: bearer,
    tags: ["docs", "knowledge"],
    capabilities: ["create document", "query database", "update page", "search workspace"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "3 req/s average",
    pricing: "Free",
  },
  {
    slug: "linear-graphql-api",
    name: "Linear GraphQL",
    category: "api",
    summary: "Issue tracking as a typed GraphQL schema — well suited to agent-driven project ops.",
    endpoint: "https://api.linear.app/graphql",
    docs_url: "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
    auth_mode: "API key in Authorization header",
    auth_params: bearer,
    tags: ["project", "issues"],
    capabilities: ["create issue", "update issue status", "query backlog", "assign work"],
    input_format: "application/json (GraphQL)",
    output_format: "application/json",
    rate_limit: "1500 req/h",
    pricing: "Free with workspace",
  },
  {
    slug: "supabase-rest-api",
    name: "Supabase PostgREST",
    category: "api",
    summary: "Any Postgres schema exposed as a REST interface with row-level security.",
    endpoint: "https://<project-ref>.supabase.co/rest/v1",
    docs_url: "https://supabase.com/docs/guides/api",
    auth_mode: "apikey header + optional user JWT",
    auth_params: [
      { name: "apikey", location: "header", required: true },
      { name: "Authorization", location: "header", required: false },
    ],
    tags: ["database", "postgres"],
    capabilities: ["query database", "insert row", "update row", "call sql function"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Instance-dependent",
    pricing: "Free tier available",
    verified: true,
  },
  {
    slug: "cloudflare-api",
    name: "Cloudflare API",
    category: "api",
    summary: "DNS, Workers, R2, KV and zone management through one REST surface.",
    endpoint: "https://api.cloudflare.com/client/v4",
    docs_url: "https://developers.cloudflare.com/api/",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["infra", "dns"],
    capabilities: ["manage dns record", "deploy worker", "purge cache", "store object"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "1200 req/5min",
    pricing: "Free tier available",
  },
  {
    slug: "openweathermap-api",
    name: "OpenWeatherMap",
    category: "api",
    summary: "Current conditions and forecasts by coordinates or city name.",
    endpoint: "https://api.openweathermap.org/data/2.5/weather",
    docs_url: "https://openweathermap.org/current",
    auth_mode: "appid query parameter",
    auth_params: [{ name: "appid", location: "query", required: true }],
    tags: ["weather", "data"],
    capabilities: ["get weather", "get forecast", "geocode city"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "60 calls/min free",
    pricing: "Free tier available",
  },
  {
    slug: "exchangerate-api",
    name: "exchangerate.host",
    category: "api",
    summary: "Foreign exchange rates and currency conversion, no signup for basic use.",
    endpoint: "https://api.exchangerate.host/latest",
    docs_url: "https://exchangerate.host/documentation",
    auth_mode: "None (access key for higher tiers)",
    tags: ["finance", "data"],
    capabilities: ["convert currency", "get exchange rate", "historical rates"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free tier",
  },
  {
    slug: "deepl-api",
    name: "DeepL",
    category: "api",
    summary: "High-quality machine translation with formality and glossary control.",
    endpoint: "https://api-free.deepl.com/v2/translate",
    docs_url: "https://developers.deepl.com/docs",
    auth_mode: "DeepL-Auth-Key header",
    auth_params: apiKeyHeader("Authorization"),
    tags: ["translation", "nlp"],
    capabilities: ["translate text", "translate document", "detect language"],
    input_format: "application/x-www-form-urlencoded",
    output_format: "application/json",
    rate_limit: "500k chars/mo free",
    pricing: "Free tier then per character",
  },
  {
    slug: "elevenlabs-api",
    name: "ElevenLabs",
    category: "api",
    summary: "Text-to-speech and voice cloning with streaming audio output.",
    endpoint: "https://api.elevenlabs.io/v1/text-to-speech",
    docs_url: "https://elevenlabs.io/docs/api-reference",
    auth_mode: "xi-api-key header",
    auth_params: apiKeyHeader("xi-api-key"),
    tags: ["audio", "ai"],
    capabilities: ["text to speech", "clone voice", "stream audio"],
    input_format: "application/json",
    output_format: "audio/mpeg stream",
    rate_limit: "Plan-based concurrency",
    pricing: "Free tier then per character",
  },
  {
    slug: "replicate-api",
    name: "Replicate",
    category: "api",
    summary: "Run open-source models (image, video, audio) behind one prediction endpoint.",
    endpoint: "https://api.replicate.com/v1/predictions",
    docs_url: "https://replicate.com/docs/reference/http",
    auth_mode: "Bearer API token",
    auth_params: bearer,
    tags: ["ai", "models"],
    capabilities: ["generate image", "generate video", "run open model", "upscale image"],
    input_format: "application/json",
    output_format: "application/json (async prediction)",
    rate_limit: "Account-based concurrency",
    pricing: "Per second of compute",
  },
  {
    slug: "hugging-face-inference-api",
    name: "Hugging Face Inference",
    category: "api",
    summary: "Serverless inference across thousands of hosted community models.",
    endpoint: "https://api-inference.huggingface.co/models",
    docs_url: "https://huggingface.co/docs/api-inference/index",
    auth_mode: "Bearer token",
    auth_params: bearer,
    tags: ["ai", "models"],
    capabilities: ["text classification", "text embedding", "image classification", "run open model"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Free tier throttled",
    pricing: "Free tier then usage-based",
  },
  {
    slug: "google-maps-places-api",
    name: "Google Places",
    category: "api",
    summary: "Place search, details and geocoding for location-aware agents.",
    endpoint: "https://places.googleapis.com/v1/places:searchText",
    docs_url: "https://developers.google.com/maps/documentation/places/web-service",
    auth_mode: "X-Goog-Api-Key header",
    auth_params: apiKeyHeader("X-Goog-Api-Key"),
    tags: ["maps", "location"],
    capabilities: ["search places", "geocode address", "get place details", "compute route"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "QPS quota per project",
    pricing: "Monthly credit then per request",
  },
  {
    slug: "airtable-api",
    name: "Airtable",
    category: "api",
    summary: "Read and write structured base records — a lightweight agent-writable datastore.",
    endpoint: "https://api.airtable.com/v0",
    docs_url: "https://airtable.com/developers/web/api/introduction",
    auth_mode: "Bearer personal access token",
    auth_params: bearer,
    tags: ["database", "nocode"],
    capabilities: ["query database", "insert row", "update row", "list records"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "5 req/s per base",
    pricing: "Free tier available",
  },
  {
    slug: "sentry-api",
    name: "Sentry",
    category: "api",
    summary: "Query issues, events and releases to let agents triage production errors.",
    endpoint: "https://sentry.io/api/0",
    docs_url: "https://docs.sentry.io/api/",
    auth_mode: "Bearer auth token",
    auth_params: bearer,
    tags: ["observability", "errors"],
    capabilities: ["list errors", "resolve issue", "read stack trace", "monitor release"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Org-based quota",
    pricing: "Free tier available",
  },
  {
    slug: "hackernews-api",
    name: "Hacker News Firebase API",
    category: "api",
    summary: "Public, auth-free feed of stories, comments and users.",
    endpoint: "https://hacker-news.firebaseio.com/v0/topstories.json",
    docs_url: "https://github.com/HackerNews/API",
    auth_mode: "None",
    tags: ["news", "public"],
    capabilities: ["read news feed", "monitor topic", "fetch comments"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "Fair use",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "wikipedia-rest-api",
    name: "Wikipedia REST",
    category: "api",
    summary: "Article summaries and full content — a reliable no-auth grounding source.",
    endpoint: "https://en.wikipedia.org/api/rest_v1/page/summary",
    docs_url: "https://en.wikipedia.org/api/rest_v1/",
    auth_mode: "None",
    tags: ["knowledge", "public"],
    capabilities: ["look up facts", "summarize article", "ground answers"],
    input_format: "path parameter",
    output_format: "application/json",
    rate_limit: "200 req/s shared",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "openalex-api",
    name: "OpenAlex",
    category: "api",
    summary: "Open catalog of scholarly works, authors and institutions.",
    endpoint: "https://api.openalex.org/works",
    docs_url: "https://docs.openalex.org",
    auth_mode: "None (polite pool via mailto)",
    tags: ["research", "public"],
    capabilities: ["search papers", "cite sources", "look up author"],
    input_format: "query string",
    output_format: "application/json",
    rate_limit: "100k req/day",
    pricing: "Free",
  },
  {
    slug: "pdf-co-api",
    name: "PDF.co",
    category: "api",
    summary: "Parse, split, merge and extract data from PDFs over HTTP.",
    endpoint: "https://api.pdf.co/v1/pdf/convert/to/text",
    docs_url: "https://developer.pdf.co",
    auth_mode: "x-api-key header",
    auth_params: apiKeyHeader("x-api-key"),
    tags: ["documents", "parsing"],
    capabilities: ["parse pdf", "extract text", "merge documents", "fill form"],
    input_format: "application/json",
    output_format: "application/json",
    rate_limit: "Plan-based",
    pricing: "Free trial credits",
  },
  {
    slug: "browserless-api",
    name: "Browserless",
    category: "api",
    summary: "Headless Chrome as a service: screenshots, PDFs and scripted browsing.",
    endpoint: "https://production-sfo.browserless.io/screenshot",
    docs_url: "https://docs.browserless.io",
    auth_mode: "token query parameter",
    auth_params: [{ name: "token", location: "query", required: true }],
    tags: ["browser", "automation"],
    capabilities: ["screenshot page", "render pdf", "browse website", "run browser automation"],
    input_format: "application/json",
    output_format: "image/png or application/pdf",
    rate_limit: "Concurrency-based",
    pricing: "Free trial then usage-based",
  },

  /* ---------------------------------------------------------- MCP servers */
  {
    slug: "github-mcp-server",
    name: "GitHub MCP Server",
    category: "mcp",
    summary: "Official MCP server exposing repos, issues, PRs and code search as tools.",
    endpoint: "https://api.githubcopilot.com/mcp/",
    docs_url: "https://github.com/github/github-mcp-server",
    auth_mode: "OAuth or PAT bearer",
    auth_params: bearer,
    tags: ["dev", "git"],
    capabilities: ["read repository", "open issue", "create pull request", "search code", "review code"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "GitHub API limits apply",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "context7-mcp-server",
    name: "Context7 MCP",
    category: "mcp",
    summary: "Up-to-date library documentation injected straight into an agent's context.",
    endpoint: "https://mcp.context7.com/mcp",
    docs_url: "https://github.com/upstash/context7",
    auth_mode: "None (optional API key)",
    tags: ["docs", "dev"],
    capabilities: ["read documentation", "resolve library id", "ground code generation"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Fair use",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "deepwiki-mcp-server",
    name: "DeepWiki MCP",
    category: "mcp",
    summary: "Ask questions about any public GitHub repository through indexed wikis.",
    endpoint: "https://mcp.deepwiki.com/mcp",
    docs_url: "https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    auth_mode: "None",
    tags: ["docs", "dev"],
    capabilities: ["read documentation", "explain codebase", "ask about repository"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Fair use",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "filesystem-mcp-server",
    name: "Filesystem MCP",
    category: "mcp",
    summary: "Reference server giving agents scoped read/write access to local directories.",
    endpoint: "npx -y @modelcontextprotocol/server-filesystem <allowed-dir>",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    auth_mode: "None (local stdio, path-scoped)",
    tags: ["files", "local"],
    capabilities: ["read file", "write file", "list directory", "search files"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "postgres-mcp-server",
    name: "Postgres MCP",
    category: "mcp",
    summary: "Read-only SQL access to a Postgres database with schema introspection.",
    endpoint: "npx -y @modelcontextprotocol/server-postgres <connection-string>",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    auth_mode: "Connection string",
    tags: ["database", "sql"],
    capabilities: ["query database", "inspect schema", "run sql"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "Database-dependent",
    pricing: "Free",
  },
  {
    slug: "playwright-mcp-server",
    name: "Playwright MCP",
    category: "mcp",
    summary: "Drive a real browser from an agent: navigate, click, type, snapshot.",
    endpoint: "npx -y @playwright/mcp@latest",
    docs_url: "https://github.com/microsoft/playwright-mcp",
    auth_mode: "None (local stdio)",
    tags: ["browser", "automation"],
    capabilities: ["browse website", "click element", "fill form", "screenshot page", "run browser automation"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results (accessibility tree)",
    rate_limit: "None",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "sentry-mcp-server",
    name: "Sentry MCP",
    category: "mcp",
    summary: "Hosted MCP server for triaging production errors and running Seer analyses.",
    endpoint: "https://mcp.sentry.dev/mcp",
    docs_url: "https://docs.sentry.io/product/sentry-mcp/",
    auth_mode: "OAuth",
    tags: ["observability", "errors"],
    capabilities: ["list errors", "read stack trace", "resolve issue", "analyze root cause"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Org quota",
    pricing: "Free with account",
  },
  {
    slug: "stripe-mcp-server",
    name: "Stripe MCP",
    category: "mcp",
    summary: "Stripe's agent toolkit exposed as MCP tools for payments and billing ops.",
    endpoint: "https://mcp.stripe.com",
    docs_url: "https://docs.stripe.com/mcp",
    auth_mode: "OAuth or restricted API key",
    auth_params: bearer,
    tags: ["payments", "billing"],
    capabilities: ["create customer", "issue refund", "payment link", "read documentation"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Stripe API limits apply",
    pricing: "Free (Stripe fees apply)",
  },
  {
    slug: "notion-mcp-server",
    name: "Notion MCP",
    category: "mcp",
    summary: "Official Notion MCP server for searching, reading and writing workspace content.",
    endpoint: "https://mcp.notion.com/mcp",
    docs_url: "https://developers.notion.com/docs/mcp",
    auth_mode: "OAuth",
    tags: ["docs", "knowledge"],
    capabilities: ["search workspace", "create document", "update page", "query database"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Notion API limits apply",
    pricing: "Free with workspace",
  },
  {
    slug: "linear-mcp-server",
    name: "Linear MCP",
    category: "mcp",
    summary: "Manage issues, projects and cycles from an agent session.",
    endpoint: "https://mcp.linear.app/sse",
    docs_url: "https://linear.app/docs/mcp",
    auth_mode: "OAuth",
    tags: ["project", "issues"],
    capabilities: ["create issue", "update issue status", "query backlog", "assign work"],
    input_format: "JSON-RPC 2.0 over SSE",
    output_format: "MCP tool results",
    rate_limit: "Linear API limits apply",
    pricing: "Free with workspace",
  },
  {
    slug: "supabase-mcp-server",
    name: "Supabase MCP",
    category: "mcp",
    summary: "Query, migrate and inspect a Supabase project through MCP tools.",
    endpoint: "npx -y @supabase/mcp-server-supabase@latest",
    docs_url: "https://supabase.com/docs/guides/getting-started/mcp",
    auth_mode: "Personal access token",
    tags: ["database", "postgres"],
    capabilities: ["query database", "inspect schema", "run migration", "read logs"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "Project-dependent",
    pricing: "Free",
  },
  {
    slug: "cloudflare-mcp-server",
    name: "Cloudflare MCP",
    category: "mcp",
    summary: "Remote MCP servers for Workers, observability, DNS analytics and docs.",
    endpoint: "https://docs.mcp.cloudflare.com/mcp",
    docs_url: "https://developers.cloudflare.com/agents/model-context-protocol/",
    auth_mode: "OAuth",
    tags: ["infra", "dns"],
    capabilities: ["deploy worker", "read documentation", "read logs", "manage dns record"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Account quota",
    pricing: "Free tier available",
  },
  {
    slug: "fetch-mcp-server",
    name: "Fetch MCP",
    category: "mcp",
    summary: "Reference server that fetches a URL and converts it to markdown for the model.",
    endpoint: "npx -y @modelcontextprotocol/server-fetch",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    auth_mode: "None",
    tags: ["web", "content"],
    capabilities: ["fetch url", "html to markdown", "read web page"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "memory-mcp-server",
    name: "Memory MCP",
    category: "mcp",
    summary: "Knowledge-graph persistent memory so agents keep state across sessions.",
    endpoint: "npx -y @modelcontextprotocol/server-memory",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    auth_mode: "None (local stdio)",
    tags: ["memory", "state"],
    capabilities: ["store memory", "recall memory", "build knowledge graph"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "sequential-thinking-mcp-server",
    name: "Sequential Thinking MCP",
    category: "mcp",
    summary: "Structured step-by-step reasoning scaffold exposed as a tool.",
    endpoint: "npx -y @modelcontextprotocol/server-sequential-thinking",
    docs_url: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    auth_mode: "None (local stdio)",
    tags: ["reasoning", "planning"],
    capabilities: ["plan a task", "decompose problem", "structured reasoning"],
    input_format: "JSON-RPC 2.0 over stdio",
    output_format: "MCP tool results",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "hugging-face-mcp-server",
    name: "Hugging Face MCP",
    category: "mcp",
    summary: "Search models, datasets and Spaces, and call hosted inference from an agent.",
    endpoint: "https://huggingface.co/mcp",
    docs_url: "https://huggingface.co/settings/mcp",
    auth_mode: "Bearer token",
    auth_params: bearer,
    tags: ["ai", "models"],
    capabilities: ["search models", "run open model", "search datasets"],
    input_format: "JSON-RPC 2.0 (MCP)",
    output_format: "MCP tool results",
    rate_limit: "Account quota",
    pricing: "Free tier",
  },

  /* ----------------------------------------------------------------- CLIs */
  {
    slug: "ffmpeg-cli",
    name: "ffmpeg",
    category: "cli",
    summary: "Universal media transcoder — the default media layer for agent pipelines.",
    endpoint: "ffmpeg -i <input> [options] <output>",
    docs_url: "https://ffmpeg.org/ffmpeg.html",
    auth_mode: "None (local binary)",
    tags: ["media", "video"],
    capabilities: ["transcode video", "extract audio", "resize video", "generate thumbnail"],
    input_format: "CLI arguments + media files",
    output_format: "Media files, stderr progress",
    rate_limit: "Local CPU bound",
    pricing: "Free (LGPL/GPL)",
    invocation_example: "ffmpeg -i input.mov -vf scale=1280:-2 -c:v libx264 output.mp4",
    verified: true,
  },
  {
    slug: "curl-cli",
    name: "curl",
    category: "cli",
    summary: "The universal HTTP client agents fall back to when no SDK exists.",
    endpoint: "curl [options] <url>",
    docs_url: "https://curl.se/docs/manpage.html",
    auth_mode: "Delegated to target service",
    tags: ["http", "network"],
    capabilities: ["call http api", "download file", "upload file", "inspect headers"],
    input_format: "CLI arguments",
    output_format: "stdout (any content type)",
    rate_limit: "None",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "jq-cli",
    name: "jq",
    category: "cli",
    summary: "JSON transformation language — glue between two agent-callable interfaces.",
    endpoint: "jq '<filter>' <file>",
    docs_url: "https://jqlang.github.io/jq/manual/",
    auth_mode: "None",
    tags: ["json", "data"],
    capabilities: ["transform json", "filter data", "reshape payload"],
    input_format: "stdin JSON",
    output_format: "stdout JSON",
    rate_limit: "None",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "ripgrep-cli",
    name: "ripgrep",
    category: "cli",
    summary: "Fast recursive code and text search, the standard agent codebase primitive.",
    endpoint: "rg <pattern> [path]",
    docs_url: "https://github.com/BurntSushi/ripgrep",
    auth_mode: "None",
    tags: ["search", "dev"],
    capabilities: ["search code", "search files", "grep text"],
    input_format: "CLI arguments",
    output_format: "stdout (matches)",
    rate_limit: "None",
    pricing: "Free",
    verified: true,
  },
  {
    slug: "git-cli",
    name: "git",
    category: "cli",
    summary: "Version control operations agents need to inspect and change codebases.",
    endpoint: "git <command> [args]",
    docs_url: "https://git-scm.com/docs",
    auth_mode: "SSH key or token",
    tags: ["dev", "git"],
    capabilities: ["read repository", "commit changes", "create branch", "diff code"],
    input_format: "CLI arguments",
    output_format: "stdout",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "gh-cli",
    name: "GitHub CLI",
    category: "cli",
    summary: "Scriptable GitHub: issues, PRs, releases and workflow runs from the shell.",
    endpoint: "gh <command> [args]",
    docs_url: "https://cli.github.com/manual/",
    auth_mode: "gh auth login / GH_TOKEN",
    tags: ["dev", "git"],
    capabilities: ["open issue", "create pull request", "trigger workflow", "read repository"],
    input_format: "CLI arguments",
    output_format: "stdout (JSON with --json)",
    rate_limit: "GitHub API limits apply",
    pricing: "Free",
  },
  {
    slug: "psql-cli",
    name: "psql",
    category: "cli",
    summary: "Direct SQL access to Postgres, scriptable and machine-parseable.",
    endpoint: "psql <connection-string> -c '<sql>'",
    docs_url: "https://www.postgresql.org/docs/current/app-psql.html",
    auth_mode: "Connection string",
    tags: ["database", "sql"],
    capabilities: ["query database", "run sql", "inspect schema", "export data"],
    input_format: "CLI arguments / stdin SQL",
    output_format: "stdout (CSV/JSON with flags)",
    rate_limit: "Database-dependent",
    pricing: "Free",
  },
  {
    slug: "imagemagick-cli",
    name: "ImageMagick",
    category: "cli",
    summary: "Convert, resize, composite and inspect images from a single command.",
    endpoint: "magick <input> [options] <output>",
    docs_url: "https://imagemagick.org/script/command-line-processing.php",
    auth_mode: "None",
    tags: ["images", "media"],
    capabilities: ["resize image", "convert image format", "composite image", "read image metadata"],
    input_format: "CLI arguments + image files",
    output_format: "Image files",
    rate_limit: "Local CPU bound",
    pricing: "Free",
  },
  {
    slug: "pandoc-cli",
    name: "pandoc",
    category: "cli",
    summary: "Convert documents between markdown, HTML, DOCX, PDF and more.",
    endpoint: "pandoc <input> -o <output>",
    docs_url: "https://pandoc.org/MANUAL.html",
    auth_mode: "None",
    tags: ["documents", "conversion"],
    capabilities: ["convert document", "html to markdown", "render pdf"],
    input_format: "CLI arguments + files",
    output_format: "Converted document files",
    rate_limit: "None",
    pricing: "Free",
  },
  {
    slug: "yt-dlp-cli",
    name: "yt-dlp",
    category: "cli",
    summary: "Download media and metadata from thousands of video platforms.",
    endpoint: "yt-dlp [options] <url>",
    docs_url: "https://github.com/yt-dlp/yt-dlp",
    auth_mode: "Optional cookies for gated content",
    tags: ["media", "download"],
    capabilities: ["download video", "extract audio", "read media metadata", "fetch subtitles"],
    input_format: "CLI arguments",
    output_format: "Media files, JSON with --dump-json",
    rate_limit: "Source-site dependent",
    pricing: "Free",
  },
  {
    slug: "aws-cli",
    name: "AWS CLI",
    category: "cli",
    summary: "Full AWS control plane — S3, Lambda, ECS and every other service.",
    endpoint: "aws <service> <command> [args]",
    docs_url: "https://docs.aws.amazon.com/cli/latest/reference/",
    auth_mode: "AWS credentials / IAM role",
    tags: ["cloud", "infra"],
    capabilities: ["store object", "deploy function", "manage infrastructure", "read logs"],
    input_format: "CLI arguments",
    output_format: "stdout JSON",
    rate_limit: "AWS service quotas",
    pricing: "Free CLI, AWS usage billed",
  },
  {
    slug: "docker-cli",
    name: "Docker CLI",
    category: "cli",
    summary: "Build and run containers — the sandbox layer for agent-executed code.",
    endpoint: "docker <command> [args]",
    docs_url: "https://docs.docker.com/reference/cli/docker/",
    auth_mode: "Local daemon socket / registry login",
    tags: ["containers", "infra"],
    capabilities: ["run container", "build image", "sandbox execution", "manage infrastructure"],
    input_format: "CLI arguments",
    output_format: "stdout (JSON with --format)",
    rate_limit: "None locally",
    pricing: "Free (Docker Engine)",
  },
  {
    slug: "sqlite3-cli",
    name: "sqlite3",
    category: "cli",
    summary: "Zero-config local SQL database, ideal for agent scratch state.",
    endpoint: "sqlite3 <file.db> '<sql>'",
    docs_url: "https://sqlite.org/cli.html",
    auth_mode: "None (file permissions)",
    tags: ["database", "sql"],
    capabilities: ["query database", "run sql", "store state", "export data"],
    input_format: "CLI arguments / stdin SQL",
    output_format: "stdout (JSON with -json)",
    rate_limit: "None",
    pricing: "Free (public domain)",
  },
  {
    slug: "tesseract-cli",
    name: "Tesseract OCR",
    category: "cli",
    summary: "Extract text from images and scans locally, no network round trip.",
    endpoint: "tesseract <image> <output-base> [options]",
    docs_url: "https://tesseract-ocr.github.io/tessdoc/",
    auth_mode: "None",
    tags: ["ocr", "documents"],
    capabilities: ["ocr image", "extract text", "parse scanned document"],
    input_format: "CLI arguments + image files",
    output_format: "Text / hOCR / TSV files",
    rate_limit: "Local CPU bound",
    pricing: "Free (Apache-2.0)",
  },
];

export const CATALOG: CatalogEntry[] = [...BASE_CATALOG, ...EXTRA_CATALOG];
