/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServerDotjsonRouteImport } from './routes/server[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated/registry'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as Char91DotwellKnownChar93McpJsonRouteImport } from './routes/[.well-known]/mcp.json'
import { Route as AuthenticatedEntrySlugRouteImport } from './routes/_authenticated/entry.$slug'
import { Route as ApiPublicDiscoverRouteImport } from './routes/api/public/discover'
import { Route as ApiPublicHealthCheckRouteImport } from './routes/api/public/health-check'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicRegistryRouteImport } from './routes/api/public/registry'
import { Route as ApiPublicReportRouteImport } from './routes/api/public/report'
import { Route as ApiPublicRegistrySlugRouteImport } from './routes/api/public/registry.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerDotjsonRoute = ServerDotjsonRouteImport.update({
  id: '/server.json',
  path: '/server.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93McpJsonRoute =
  Char91DotwellKnownChar93McpJsonRouteImport.update({
    id: '/.well-known/mcp/json',
    path: '/.well-known/mcp/json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEntrySlugRoute = AuthenticatedEntrySlugRouteImport.update({
  id: '/entry/$slug',
  path: '/entry/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDiscoverRoute = ApiPublicDiscoverRouteImport.update({
  id: '/api/public/discover',
  path: '/api/public/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthCheckRoute = ApiPublicHealthCheckRouteImport.update({
  id: '/api/public/health-check',
  path: '/api/public/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegistryRoute = ApiPublicRegistryRouteImport.update({
  id: '/api/public/registry',
  path: '/api/public/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReportRoute = ApiPublicReportRouteImport.update({
  id: '/api/public/report',
  path: '/api/public/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegistrySlugRoute = ApiPublicRegistrySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicRegistryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/server.json': typeof ServerDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/.well-known/mcp/json': typeof Char91DotwellKnownChar93McpJsonRoute
  '/entry/$slug': typeof AuthenticatedEntrySlugRoute
  '/api/public/discover': typeof ApiPublicDiscoverRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/registry': typeof ApiPublicRegistryRouteWithChildren
  '/api/public/report': typeof ApiPublicReportRoute
  '/api/public/registry/$slug': typeof ApiPublicRegistrySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/server.json': typeof ServerDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/.well-known/mcp/json': typeof Char91DotwellKnownChar93McpJsonRoute
  '/entry/$slug': typeof AuthenticatedEntrySlugRoute
  '/api/public/discover': typeof ApiPublicDiscoverRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/registry': typeof ApiPublicRegistryRouteWithChildren
  '/api/public/report': typeof ApiPublicReportRoute
  '/api/public/registry/$slug': typeof ApiPublicRegistrySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/server.json': typeof ServerDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/.well-known/mcp/json': typeof Char91DotwellKnownChar93McpJsonRoute
  '/_authenticated/entry/$slug': typeof AuthenticatedEntrySlugRoute
  '/api/public/discover': typeof ApiPublicDiscoverRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/registry': typeof ApiPublicRegistryRouteWithChildren
  '/api/public/report': typeof ApiPublicReportRoute
  '/api/public/registry/$slug': typeof ApiPublicRegistrySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/server.json'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/registry'
    | '/signals'
    | '/submit'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/.well-known/mcp/json'
    | '/entry/$slug'
    | '/api/public/discover'
    | '/api/public/health-check'
    | '/api/public/ingest'
    | '/api/public/registry'
    | '/api/public/report'
    | '/api/public/registry/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/server.json'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/registry'
    | '/signals'
    | '/submit'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/.well-known/mcp/json'
    | '/entry/$slug'
    | '/api/public/discover'
    | '/api/public/health-check'
    | '/api/public/ingest'
    | '/api/public/registry'
    | '/api/public/report'
    | '/api/public/registry/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/server.json'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/registry'
    | '/_authenticated/signals'
    | '/_authenticated/submit'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/.well-known/mcp/json'
    | '/_authenticated/entry/$slug'
    | '/api/public/discover'
    | '/api/public/health-check'
    | '/api/public/ingest'
    | '/api/public/registry'
    | '/api/public/report'
    | '/api/public/registry/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  ExploreRoute: typeof ExploreRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  ServerDotjsonRoute: typeof ServerDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  Char91DotwellKnownChar93McpJsonRoute: typeof Char91DotwellKnownChar93McpJsonRoute
  ApiPublicDiscoverRoute: typeof ApiPublicDiscoverRoute
  ApiPublicHealthCheckRoute: typeof ApiPublicHealthCheckRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicRegistryRoute: typeof ApiPublicRegistryRouteWithChildren
  ApiPublicReportRoute: typeof ApiPublicReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server.json': {
      id: '/server.json'
      path: '/server.json'
      fullPath: '/server.json'
      preLoaderRoute: typeof ServerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/json': {
      id: '/.well-known/mcp/json'
      path: '/.well-known/mcp/json'
      fullPath: '/.well-known/mcp/json'
      preLoaderRoute: typeof Char91DotwellKnownChar93McpJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entry/$slug': {
      id: '/_authenticated/entry/$slug'
      path: '/entry/$slug'
      fullPath: '/entry/$slug'
      preLoaderRoute: typeof AuthenticatedEntrySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/discover': {
      id: '/api/public/discover'
      path: '/api/public/discover'
      fullPath: '/api/public/discover'
      preLoaderRoute: typeof ApiPublicDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-check': {
      id: '/api/public/health-check'
      path: '/api/public/health-check'
      fullPath: '/api/public/health-check'
      preLoaderRoute: typeof ApiPublicHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/registry': {
      id: '/api/public/registry'
      path: '/api/public/registry'
      fullPath: '/api/public/registry'
      preLoaderRoute: typeof ApiPublicRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/report': {
      id: '/api/public/report'
      path: '/api/public/report'
      fullPath: '/api/public/report'
      preLoaderRoute: typeof ApiPublicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/registry/$slug': {
      id: '/api/public/registry/$slug'
      path: '/$slug'
      fullPath: '/api/public/registry/$slug'
      preLoaderRoute: typeof ApiPublicRegistrySlugRouteImport
      parentRoute: typeof ApiPublicRegistryRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedEntrySlugRoute: typeof AuthenticatedEntrySlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedEntrySlugRoute: AuthenticatedEntrySlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicRegistryRouteChildren {
  ApiPublicRegistrySlugRoute: typeof ApiPublicRegistrySlugRoute
}

const ApiPublicRegistryRouteChildren: ApiPublicRegistryRouteChildren = {
  ApiPublicRegistrySlugRoute: ApiPublicRegistrySlugRoute,
}

const ApiPublicRegistryRouteWithChildren =
  ApiPublicRegistryRoute._addFileChildren(ApiPublicRegistryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  ExploreRoute: ExploreRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  ServerDotjsonRoute: ServerDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  Char91DotwellKnownChar93McpJsonRoute: Char91DotwellKnownChar93McpJsonRoute,
  ApiPublicDiscoverRoute: ApiPublicDiscoverRoute,
  ApiPublicHealthCheckRoute: ApiPublicHealthCheckRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicRegistryRoute: ApiPublicRegistryRouteWithChildren,
  ApiPublicReportRoute: ApiPublicReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
