INSERT INTO public.entries (slug, name, category, summary, description, auth_mode, endpoint, docs_url, tags, status)
VALUES
('stripe-api','Stripe','api','Payments, subscriptions, invoices. Idempotent writes, cursor pagination.','REST API with idempotency keys, cursor pagination and webhooks. One of the most reliable contracts an agent can build on.','Bearer secret key','https://api.stripe.com/v1','https://docs.stripe.com/api',ARRAY['payments','billing'],'approved'),
('notion-api','Notion','api','Pages, databases and blocks as structured JSON. Rate limit ~3 req/s.','Structured content API. Good fit for knowledge-retrieval agents; watch the ~3 req/s rate limit.','Bearer integration token','https://api.notion.com/v1','https://developers.notion.com/reference/intro',ARRAY['docs','knowledge'],'approved'),
('resend-api','Resend','api','Transactional email with a single POST. Ideal for agent side effects.','Single-endpoint transactional email. Minimal surface, easy for an agent to call correctly.','Bearer API key','https://api.resend.com/emails','https://resend.com/docs/api-reference/introduction',ARRAY['email'],'approved'),
('linear-api','Linear','api','GraphQL issue tracker. Strong schema, great for planning agents.','GraphQL API with a strict schema, which makes tool-call generation reliable.','API key header','https://api.linear.app/graphql','https://developers.linear.app/docs',ARRAY['issues','graphql'],'approved'),
('supabase-mcp','Supabase MCP','mcp','Query and mutate Postgres, inspect schema, manage projects over MCP.','Remote MCP server exposing database, schema and project management tools.','OAuth 2.1 / PAT','https://mcp.supabase.com/mcp','https://supabase.com/docs/guides/getting-started/mcp',ARRAY['database','sql'],'approved'),
('github-mcp','GitHub MCP','mcp','Repos, issues, pull requests and code search as first-class tools.','Official remote MCP server for GitHub, with OAuth 2.1 and fine-grained tool scopes.','OAuth 2.1','https://api.githubcopilot.com/mcp','https://github.com/github/github-mcp-server',ARRAY['code','vcs'],'approved'),
('sentry-mcp','Sentry MCP','mcp','Error groups, stack traces and release health for debugging agents.','Remote MCP server giving agents access to issues, traces and release health.','OAuth 2.1','https://mcp.sentry.dev/mcp','https://docs.sentry.io/product/sentry-mcp/',ARRAY['observability'],'approved'),
('cloudflare-mcp','Cloudflare MCP','mcp','Workers, DNS, analytics and logs exposed as remote MCP tools.','Remote MCP servers for Cloudflare observability and edge infrastructure.','OAuth 2.1','https://observability.mcp.cloudflare.com/mcp','https://developers.cloudflare.com/agents/model-context-protocol/',ARRAY['edge','infra'],'approved'),
('gh-cli','gh','cli','GitHub from the shell. `gh pr create`, `gh issue list --json` for parsing.','Machine-readable output via --json makes this one of the best agent-native CLIs.','gh auth login','gh <command> --json','https://cli.github.com/manual/',ARRAY['vcs','json-output'],'approved'),
('psql-cli','psql','cli','Direct SQL access. `psql -c "..." --csv` gives agent-parseable output.','Deterministic SQL execution with CSV output, ideal for data agents.','connection string','psql $DATABASE_URL -c','https://www.postgresql.org/docs/current/app-psql.html',ARRAY['database'],'approved'),
('ffmpeg-cli','ffmpeg','cli','Media transcoding an agent can drive deterministically from a prompt.','Complete media pipeline callable from a single command line.','none','ffmpeg -i in.mp4 out.webm','https://ffmpeg.org/documentation.html',ARRAY['media'],'approved'),
('curl-cli','curl','cli','The universal fallback when no SDK or MCP server exists yet.','Raw HTTP client; the lowest common denominator for any agent integration.','per target','curl -sS -H ''Authorization: ...''','https://curl.se/docs/manpage.html',ARRAY['http'],'approved')
ON CONFLICT (slug) DO NOTHING;